import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';

import { createDefaultReportViewSnapshot } from '../../src/hooks/useReportViewState';
import { DEFAULT_PLANNING_MAP_STATE } from '../../src/engine/planningMapState';
import type { WorkspaceDraftSnapshot } from '../../src/appStateTypes';

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

export { act, createRoot, type Root };
export const STORAGE_KEY = 'webnet.workspace-recovery.test';
export const defaultReportViewSnapshot = createDefaultReportViewSnapshot();

export const buildSnapshot = (overrides: Partial<WorkspaceDraftSnapshot> = {}): WorkspaceDraftSnapshot => ({
  input: 'INPUT',
  projectIncludeFiles: {},
  settings: {
    maxIterations: 10,
    convergenceLimit: 0.01,
    units: 'm',
    uiTheme: 'gruvbox-dark',
    mapShowLostStations: true,
    map3dEnabled: false,
    showRunComparisonPanel: false,
    showReviewQueuePanel: false,
    listingShowLostStations: true,
    listingShowCoordinates: true,
    listingShowObservationsResiduals: true,
    listingShowErrorPropagation: true,
    listingShowProcessingNotes: true,
    listingShowAzimuthsBearings: true,
    listingSortCoordinatesBy: 'name',
    listingSortObservationsBy: 'stdResidual',
    listingObservationLimit: 60,
  },
  parseSettings: {
    solveProfile: 'industry-parity',
    coordMode: '3D',
    coordSystemMode: 'local',
    crsId: 'LOCAL',
    localDatumScheme: 'average-scale',
    averageScaleFactor: 1,
    commonElevation: 0,
    averageGeoidHeight: 0,
    gnssVectorFrameDefault: 'gridNEU',
    gnssFrameConfirmed: false,
    verticalDeflectionNorthSec: 0,
    verticalDeflectionEastSec: 0,
    observationMode: {
      bearing: 'grid',
      distance: 'measured',
      angle: 'measured',
      direction: 'measured',
    },
    gridBearingMode: 'grid',
    gridDistanceMode: 'measured',
    gridAngleMode: 'measured',
    gridDirectionMode: 'measured',
    runMode: 'adjustment',
    preanalysisMode: false,
    clusterDetectionEnabled: false,
    autoSideshotEnabled: true,
    autoAdjustEnabled: false,
    autoAdjustMaxCycles: 3,
    autoAdjustMaxRemovalsPerCycle: 1,
    autoAdjustStdResThreshold: 4,
    suspectImpactMode: 'auto',
    order: 'EN',
    angleUnits: 'dms',
    angleStationOrder: 'atfromto',
    angleMode: 'auto',
    deltaMode: 'slope',
    mapMode: 'off',
    mapScaleFactor: 1,
    normalize: true,
    faceNormalizationMode: 'on',
    applyCurvatureRefraction: false,
    refractionCoefficient: 0.13,
    verticalReduction: 'none',
    levelWeight: undefined,
    levelLoopToleranceBaseMm: 0,
    levelLoopTolerancePerSqrtKmMm: 4,
    crsTransformEnabled: false,
    crsProjectionModel: 'legacy-equirectangular',
    crsLabel: '',
    crsGridScaleEnabled: false,
    crsGridScaleFactor: 1,
    crsConvergenceEnabled: false,
    crsConvergenceAngleRad: 0,
    geoidModelEnabled: false,
    geoidModelId: 'NGS-DEMO',
    geoidSourceFormat: 'builtin',
    geoidSourcePath: '',
    geoidInterpolation: 'bilinear',
    geoidHeightConversionEnabled: false,
    geoidOutputHeightDatum: 'orthometric',
    gpsLoopCheckEnabled: false,
    gpsAddHiHtEnabled: false,
    gpsAddHiHtHiM: 0,
    gpsAddHiHtHtM: 0,
    qFixLinearSigmaM: 1e-7,
    qFixAngularSigmaSec: 0.0010001,
    prismEnabled: false,
    prismOffset: 0,
    prismScope: 'global',
    directionSetMode: 'reduced',
    descriptionReconcileMode: 'first',
    descriptionAppendDelimiter: ' | ',
    lonSign: 'west-negative',
    tsCorrelationEnabled: false,
    tsCorrelationRho: 0.25,
    tsCorrelationScope: 'set',
    robustMode: 'none',
    robustK: 1.5,
    parseCompatibilityMode: 'strict',
    parseModeMigrated: true,
  },
  exportFormat: 'points',
  adjustedPointsExportSettings: {
    presetId: 'PNEZ',
    format: 'csv',
    delimiter: 'comma',
    includeLostStations: true,
    columns: ['P', 'N', 'E', 'Z'],
    transform: {
      referenceStationId: '',
      scope: 'all',
      selectedStationIds: [],
      rotation: { enabled: false, angleDeg: 0 },
      translation: { enabled: false, method: 'direction-distance', azimuthDeg: 0, distance: 0, targetE: 0, targetN: 0 },
      scale: { enabled: false, factor: 1 },
    },
  },
  projectInstruments: {},
  selectedInstrument: 'S9',
  levelLoopCustomPresets: [],
  geoidSourceDataBase64: null,
  geoidSourceDataLabel: '',
  view: {
    activeTab: 'report',
    splitPercent: 35,
    isSidebarOpen: true,
    planningMap: {
      ...DEFAULT_PLANNING_MAP_STATE,
      blockedPolygons: [
        {
          id: 'block-1',
          source: 'user',
          kind: 'blocked-area',
          label: 'Blocked',
          vertices: [
            { x: 1, y: 1 },
            { x: 3, y: 1 },
            { x: 2, y: 2 },
          ],
        },
      ],
    },
    review: {
      reportView: { ...defaultReportViewSnapshot },
      selection: {
        stationId: null,
        observationId: null,
        sourceLine: null,
        origin: null,
      },
      pinnedObservationIds: [],
      runFreshness: 'ready',
      blockingReasons: [],
    },
  },
  comparisonView: {
    stationMovementThreshold: 0.001,
    residualDeltaThreshold: 0.25,
  },
  savedRunSnapshots: [],
  importReview: null,
  ...overrides,
});
