import { dmsToRad } from '../../engine/angles';
import {
  cadPointFromBearingDistance,
} from '../../engine/cad/cadCogo';
import {
  cadParseBearingDegrees,
  cadPointFromAzimuthDistance,
} from '../../engine/cad/cadGeometry';
import type { CommandPoint } from './useSurveyCadCommandTypes';

const isNumeric = (value: string): boolean => value.trim().length > 0 && Number.isFinite(Number(value));

const splitLabelFromBody = (token: string): { label?: string; body: string } => {
  const normalized = token.trim();
  const labelIndex = normalized.indexOf('=');
  if (labelIndex < 0) return { body: normalized };
  return {
    label: normalized.slice(0, labelIndex).trim() || undefined,
    body: normalized.slice(labelIndex + 1).trim(),
  };
};

export const parseAbsolutePoint = (token: string): CommandPoint | null => {
  const { label, body } = splitLabelFromBody(token);
  if (body.length === 0) return null;
  const parts = body.split(',').map((part) => part.trim());
  if (parts.length !== 2 || !isNumeric(parts[0]) || !isNumeric(parts[1])) return null;
  const x = Number(parts[0]);
  const y = Number(parts[1]);
  return {
    x,
    y,
    label: label || `${x.toFixed(3)},${y.toFixed(3)}`,
  };
};

const inputHasExplicitLabel = (token: string): boolean => {
  const { label } = splitLabelFromBody(token);
  return label != null && label.length > 0;
};

const isAutoGeneratedPointLabel = (point: CommandPoint): boolean =>
  point.label === `${point.x.toFixed(3)},${point.y.toFixed(3)}` ||
  /^cad\d+$/i.test(point.label) ||
  /^tp\d+$/i.test(point.label);

const nextAutoPointOrdinal = (
  points: readonly CommandPoint[],
  existingStationIds: readonly string[],
): number => {
  let maxOrdinal = 0;
  existingStationIds.forEach((stationId) => {
    const match = /^cad(\d+)$/i.exec(stationId);
    if (!match) return;
    maxOrdinal = Math.max(maxOrdinal, Number.parseInt(match[1] ?? '0', 10));
  });
  points.forEach((point) => {
    const match = /^cad(\d+)$/i.exec(point.label) ?? /^tp(\d+)$/i.exec(point.label);
    if (!match) return;
    maxOrdinal = Math.max(maxOrdinal, Number.parseInt(match[1] ?? '0', 10));
  });
  return maxOrdinal + 1;
};

export const normalizeDraftPoint = (
  point: CommandPoint,
  existingPoints: readonly CommandPoint[],
  existingStationIds: readonly string[],
  options?: { rawInput?: string },
): CommandPoint => {
  const shouldAutoLabel =
    options?.rawInput != null
      ? !inputHasExplicitLabel(options.rawInput)
      : isAutoGeneratedPointLabel(point);
  if (!shouldAutoLabel) return point;
  return {
    ...point,
    label: `CAD${nextAutoPointOrdinal(existingPoints, existingStationIds)}`,
  };
};

const parseRelativeBearingDistance = (
  token: string,
  basePoint: CommandPoint | null,
): CommandPoint | null => {
  if (!basePoint) return null;
  const { label, body } = splitLabelFromBody(token);
  if (body.length === 0) return null;
  const trimmed = body.trim();
  const prefixed = trimmed.startsWith('@');
  const directionBody = prefixed ? trimmed.slice(1).trim() : trimmed;
  const parts = directionBody.split(',').map((part) => part.trim());
  if (parts.length !== 2 || !isNumeric(parts[1])) return null;
  const directionToken = parts[0];
  const distance = Number(parts[1]);
  const looksLikeBearing = /^[NS]/i.test(directionToken);
  if (!prefixed && !looksLikeBearing) return null;
  const azimuthDeg = looksLikeBearing
    ? cadParseBearingDegrees(directionToken)
    : isNumeric(directionToken)
      ? Number(directionToken)
      : null;
  if (azimuthDeg == null) return null;
  const point = looksLikeBearing
    ? cadPointFromBearingDistance(basePoint, directionToken, distance)
    : cadPointFromAzimuthDistance(basePoint, azimuthDeg, distance);
  if (!point) return null;
  return {
    ...point,
    label: label || `${prefixed ? '@' : ''}${directionToken},${distance}`,
  };
};

export const parseInputPoint = (
  inputValue: string,
  basePoint: CommandPoint | null,
): CommandPoint | null =>
  parseRelativeBearingDistance(inputValue, basePoint) ?? parseAbsolutePoint(inputValue);

export const parseAngleValueDeg = (token: string): number | null => {
  const trimmed = token.trim();
  if (trimmed.length === 0) return null;
  if (/^[+-]?\d{1,3}-\d{1,2}-\d{1,2}(?:\.\d+)?$/.test(trimmed)) {
    return (dmsToRad(trimmed) * 180) / Math.PI;
  }
  const numeric = Number(trimmed);
  return Number.isFinite(numeric) ? numeric : null;
};

export const parseLeftRightAngleDistance = (
  token: string,
): { label?: string; side: 'left' | 'right'; angleDeg: number; distance: number } | null => {
  const { label, body } = splitLabelFromBody(token);
  const match = /^([LR])\s*([^,]+)\s*,\s*([-+]?\d*\.?\d+)\s*$/i.exec(body);
  if (!match) return null;
  const angleDeg = parseAngleValueDeg(match[2] ?? '');
  const distance = Number(match[3]);
  if (angleDeg == null || !Number.isFinite(distance) || distance <= 0) return null;
  return {
    label,
    side: (match[1] ?? '').toUpperCase() === 'L' ? 'left' : 'right',
    angleDeg,
    distance,
  };
};

export const parseDistanceOrPercent = (
  token: string,
): { label?: string; distance?: number; fraction?: number } | null => {
  const { label, body } = splitLabelFromBody(token);
  const trimmed = body.trim();
  if (trimmed.endsWith('%')) {
    const percent = Number(trimmed.slice(0, -1));
    if (!Number.isFinite(percent)) return null;
    return { label, fraction: percent / 100 };
  }
  const distance = Number(trimmed);
  if (!Number.isFinite(distance)) return null;
  return { label, distance };
};

export const parseOffsetPointInput = (
  token: string,
): { label?: string; side: 'left' | 'right'; offsetDistance: number; alongDistance?: number; alongFraction?: number } | null => {
  const { label, body } = splitLabelFromBody(token);
  const match = /^([LR])\s*([-+]?\d*\.?\d+)\s*,\s*(.+)$/i.exec(body);
  if (!match) return null;
  const offsetDistance = Number(match[2]);
  const along = parseDistanceOrPercent(match[3] ?? '');
  if (!Number.isFinite(offsetDistance) || !along) return null;
  return {
    label,
    side: (match[1] ?? '').toUpperCase() === 'L' ? 'left' : 'right',
    offsetDistance,
    alongDistance: along.distance,
    alongFraction: along.fraction,
  };
};

export const parseAlignmentStationOffsetInput = (
  token: string,
): { label?: string; station: number; offset: number } | null => {
  const { label, body } = splitLabelFromBody(token);
  const parts = body.split(',').map((part) => part.trim());
  if (parts.length !== 2) return null;
  const station = Number(parts[0]);
  const offset = Number(parts[1]);
  if (!Number.isFinite(station) || !Number.isFinite(offset)) return null;
  return { label, station, offset };
};

export const parseAlignmentOffsetCreateInput = (
  token: string,
): { name?: string; offset: number } | null => {
  const { label, body } = splitLabelFromBody(token);
  const offset = Number(body.trim());
  if (!Number.isFinite(offset) || Math.abs(offset) <= 1e-9) return null;
  return { name: label, offset };
};

export const parseAlignmentStationEquationInput = (
  token: string,
): { backStation: number; aheadStation: number } | null => {
  const { body } = splitLabelFromBody(token);
  const parts = body.split(',').map((part) => part.trim());
  if (parts.length !== 2) return null;
  const backStation = Number(parts[0]);
  const aheadStation = Number(parts[1]);
  if (!Number.isFinite(backStation) || !Number.isFinite(aheadStation) || aheadStation < backStation) {
    return null;
  }
  return { backStation, aheadStation };
};

export const parseAlignmentIntervalInput = (
  token: string,
): { labelPrefix?: string; startStation?: number; endStation?: number; interval: number } | null => {
  const { label, body } = splitLabelFromBody(token);
  const parts = body.split(',').map((part) => part.trim());
  if (parts.length === 1) {
    const interval = Number(parts[0]);
    if (!Number.isFinite(interval) || interval <= 0) return null;
    return {
      labelPrefix: label,
      interval,
    };
  }
  if (parts.length === 3) {
    const startStation = Number(parts[0]);
    const endStation = Number(parts[1]);
    const interval = Number(parts[2]);
    if (
      !Number.isFinite(startStation) ||
      !Number.isFinite(endStation) ||
      !Number.isFinite(interval) ||
      interval <= 0 ||
      endStation < startStation
    ) {
      return null;
    }
    return {
      labelPrefix: label,
      startStation,
      endStation,
      interval,
    };
  }
  return null;
};

export const parseDualBearingInput = (
  token: string,
): { firstBearing: string; secondBearing: string } | null => {
  const parts = token.split(/[;|]/).map((part) => part.trim()).filter((part) => part.length > 0);
  if (parts.length !== 2) return null;
  if (cadParseBearingDegrees(parts[0]) == null || cadParseBearingDegrees(parts[1]) == null) return null;
  return {
    firstBearing: parts[0]!,
    secondBearing: parts[1]!,
  };
};

export const parseBearingDistanceIntersectionInput = (
  token: string,
): { bearing: string; distance: number } | null => {
  const parts = token.split(/[;|]/).map((part) => part.trim()).filter((part) => part.length > 0);
  if (parts.length !== 2) return null;
  const distance = Number(parts[1]);
  if (cadParseBearingDegrees(parts[0]) == null || !Number.isFinite(distance) || distance < 0) return null;
  return {
    bearing: parts[0]!,
    distance,
  };
};

export const parseDistancePairInput = (
  token: string,
): { firstDistance: number; secondDistance: number } | null => {
  const parts = token.split(',').map((part) => part.trim());
  if (parts.length !== 2) return null;
  const firstDistance = Number(parts[0]);
  const secondDistance = Number(parts[1]);
  if (!Number.isFinite(firstDistance) || !Number.isFinite(secondDistance)) return null;
  return { firstDistance, secondDistance };
};

export const parseSideDistanceInput = (
  token: string,
): { side: 'left' | 'right'; distance: number } | null => {
  const match = /^([LR])\s*([-+]?\d*\.?\d+)\s*$/i.exec(token.trim());
  if (!match) return null;
  const distance = Number(match[2]);
  if (!Number.isFinite(distance)) return null;
  return {
    side: (match[1] ?? '').toUpperCase() === 'L' ? 'left' : 'right',
    distance,
  };
};

export const parseDualOffsetInput = (
  token: string,
): { firstOffset: number; secondOffset: number } | null => {
  const parts = token.split(',').map((part) => part.trim());
  if (parts.length !== 2) return null;
  const first = parseSideDistanceInput(parts[0] ?? '');
  const second = parseSideDistanceInput(parts[1] ?? '');
  if (!first || !second) return null;
  return {
    firstOffset: first.side === 'left' ? first.distance : -first.distance,
    secondOffset: second.side === 'left' ? second.distance : -second.distance,
  };
};

export const parseCurveSolverInput = (
  token: string,
):
  | {
      pair:
        | 'radius-delta'
        | 'radius-arc'
        | 'radius-chord'
        | 'radius-tangent'
        | 'delta-arc'
        | 'delta-chord'
        | 'delta-tangent'
        | 'arc-chord'
        | 'arc-tangent'
        | 'chord-tangent';
      firstValue: number;
      secondValue: number;
    }
  | null => {
  const parts = token.split(',').map((part) => part.trim());
  if (parts.length !== 4) return null;
  const pair = `${parts[0].toLowerCase()}-${parts[1].toLowerCase()}` as
    | 'radius-delta'
    | 'radius-arc'
    | 'radius-chord'
    | 'radius-tangent'
    | 'delta-arc'
    | 'delta-chord'
    | 'delta-tangent'
    | 'arc-chord'
    | 'arc-tangent'
    | 'chord-tangent';
  const allowedPairs = new Set([
    'radius-delta',
    'radius-arc',
    'radius-chord',
    'radius-tangent',
    'delta-arc',
    'delta-chord',
    'delta-tangent',
    'arc-chord',
    'arc-tangent',
    'chord-tangent',
  ]);
  if (!allowedPairs.has(pair)) return null;
  const firstValue = Number(parts[2]);
  const secondValue = Number(parts[3]);
  if (!Number.isFinite(firstValue) || !Number.isFinite(secondValue)) return null;
  return { pair, firstValue, secondValue };
};

export const parseCurveSideRadiusDeltaInput = (
  token: string,
): { side: 'left' | 'right'; radius: number; deltaDeg: number } | null => {
  const match = /^([LR])\s*([-+]?\d*\.?\d+)\s*,\s*([^,]+)\s*$/i.exec(token.trim());
  if (!match) return null;
  const radius = Number(match[2]);
  const deltaDeg = parseAngleValueDeg(match[3] ?? '');
  if (!Number.isFinite(radius) || radius <= 0 || deltaDeg == null || deltaDeg <= 0) return null;
  return {
    side: (match[1] ?? '').toUpperCase() === 'L' ? 'left' : 'right',
    radius,
    deltaDeg,
  };
};

export const parseCurveMeasureInput = (
  token: string,
): { mode: 'arc' | 'chord'; distance: number } | null => {
  const match = /^(ARC|CHORD)\s*[,; ]\s*([-+]?\d*\.?\d+)\s*$/i.exec(token.trim());
  if (!match) return null;
  const distance = Number(match[2]);
  if (!Number.isFinite(distance) || distance < 0) return null;
  return {
    mode: (match[1] ?? '').toUpperCase() === 'ARC' ? 'arc' : 'chord',
    distance,
  };
};

export const parseCurveSubdivisionInput = (
  token: string,
): { mode: 'equal' | 'arc' | 'chord'; value: number } | null => {
  const match = /^(EQUAL|ARC|CHORD)\s*[,; ]\s*([-+]?\d*\.?\d+)\s*$/i.exec(token.trim());
  if (!match) return null;
  const value = Number(match[2]);
  if (!Number.isFinite(value) || value <= 0) return null;
  return {
    mode: (match[1] ?? '').toLowerCase() as 'equal' | 'arc' | 'chord',
    value,
  };
};

export const parseOffsetArcInput = (
  token: string,
): { side: 'left' | 'right'; offsetDistance: number } | null => {
  const match = /^([LR])\s*([-+]?\d*\.?\d+)\s*$/i.exec(token.trim());
  if (!match) return null;
  const offsetDistance = Number(match[2]);
  if (!Number.isFinite(offsetDistance) || offsetDistance <= 0) return null;
  return {
    side: (match[1] ?? '').toUpperCase() === 'L' ? 'left' : 'right',
    offsetDistance,
  };
};

export const parseChordBearingCurveInput = (
  token: string,
): { chordBearing: string; chordDistance: number; radius: number; side: 'left' | 'right' } | null => {
  const parts = token.split(',').map((part) => part.trim());
  if (parts.length !== 4) return null;
  const chordDistance = Number(parts[1]);
  const radius = Number(parts[2]);
  const sideToken = parts[3]?.toUpperCase();
  if (
    cadParseBearingDegrees(parts[0] ?? '') == null ||
    !Number.isFinite(chordDistance) ||
    chordDistance <= 0 ||
    !Number.isFinite(radius) ||
    radius <= 0 ||
    (sideToken !== 'L' && sideToken !== 'R')
  ) {
    return null;
  }
  return {
    chordBearing: parts[0]!,
    chordDistance,
    radius,
    side: sideToken === 'L' ? 'left' : 'right',
  };
};
