import {
  cadPointFromBearingDistance,
} from '../../engine/cad/cadCogo';
import {
  cadParseBearingDegrees,
  cadPointFromAzimuthDistance,
} from '../../engine/cad/cadGeometry';
import type { CommandPoint } from './useSurveyCadCommandTypes';

export const isNumeric = (value: string): boolean =>
  value.trim().length > 0 && Number.isFinite(Number(value));

export const splitLabelFromBody = (token: string): { label?: string; body: string } => {
  const normalized = token.trim();
  const labelIndex = normalized.indexOf('=');
  if (labelIndex < 0) return { body: normalized };
  return {
    label: normalized.slice(0, labelIndex).trim() || undefined,
    body: normalized.slice(labelIndex + 1).trim(),
  };
};

export const parseAbsolutePoint = (token: string): CommandPoint | null => {
  const { label, body } = splitLabelFromBody(token);
  if (body.length === 0) return null;
  const parts = body.split(',').map((part) => part.trim());
  if (parts.length !== 2 || !isNumeric(parts[0]) || !isNumeric(parts[1])) return null;
  const x = Number(parts[0]);
  const y = Number(parts[1]);
  return {
    x,
    y,
    label: label || `${x.toFixed(3)},${y.toFixed(3)}`,
  };
};

const inputHasExplicitLabel = (token: string): boolean => {
  const { label } = splitLabelFromBody(token);
  return label != null && label.length > 0;
};

const isAutoGeneratedPointLabel = (point: CommandPoint): boolean =>
  point.label === `${point.x.toFixed(3)},${point.y.toFixed(3)}` ||
  /^cad\d+$/i.test(point.label) ||
  /^tp\d+$/i.test(point.label);

const nextAutoPointOrdinal = (
  points: readonly CommandPoint[],
  existingStationIds: readonly string[],
): number => {
  let maxOrdinal = 0;
  existingStationIds.forEach((stationId) => {
    const match = /^cad(\d+)$/i.exec(stationId);
    if (!match) return;
    maxOrdinal = Math.max(maxOrdinal, Number.parseInt(match[1] ?? '0', 10));
  });
  points.forEach((point) => {
    const match = /^cad(\d+)$/i.exec(point.label) ?? /^tp(\d+)$/i.exec(point.label);
    if (!match) return;
    maxOrdinal = Math.max(maxOrdinal, Number.parseInt(match[1] ?? '0', 10));
  });
  return maxOrdinal + 1;
};

export const normalizeDraftPoint = (
  point: CommandPoint,
  existingPoints: readonly CommandPoint[],
  existingStationIds: readonly string[],
  options?: { rawInput?: string },
): CommandPoint => {
  const shouldAutoLabel =
    options?.rawInput != null
      ? !inputHasExplicitLabel(options.rawInput)
      : isAutoGeneratedPointLabel(point);
  if (!shouldAutoLabel) return point;
  return {
    ...point,
    label: `CAD${nextAutoPointOrdinal(existingPoints, existingStationIds)}`,
  };
};

const parseRelativeBearingDistance = (
  token: string,
  basePoint: CommandPoint | null,
): CommandPoint | null => {
  if (!basePoint) return null;
  const { label, body } = splitLabelFromBody(token);
  if (body.length === 0) return null;
  const trimmed = body.trim();
  const prefixed = trimmed.startsWith('@');
  const directionBody = prefixed ? trimmed.slice(1).trim() : trimmed;
  const parts = directionBody.split(',').map((part) => part.trim());
  if (parts.length !== 2 || !isNumeric(parts[1])) return null;
  const directionToken = parts[0];
  const distance = Number(parts[1]);
  const looksLikeBearing = /^[NS]/i.test(directionToken);
  if (!prefixed && !looksLikeBearing) return null;
  const azimuthDeg = looksLikeBearing
    ? cadParseBearingDegrees(directionToken)
    : isNumeric(directionToken)
      ? Number(directionToken)
      : null;
  if (azimuthDeg == null) return null;
  const point = looksLikeBearing
    ? cadPointFromBearingDistance(basePoint, directionToken, distance)
    : cadPointFromAzimuthDistance(basePoint, azimuthDeg, distance);
  if (!point) return null;
  return {
    ...point,
    label: label || `${prefixed ? '@' : ''}${directionToken},${distance}`,
  };
};

export const parseInputPoint = (
  inputValue: string,
  basePoint: CommandPoint | null,
): CommandPoint | null =>
  parseRelativeBearingDistance(inputValue, basePoint) ?? parseAbsolutePoint(inputValue);
