export interface SurveyCadCommandLineProps {
  selectionCount: number;
  entityCount: number;
  canUndo: boolean;
  canRedo: boolean;
  historyDepth: number;
  redoDepth: number;
  canUseSelectedLineCoreCogo: boolean;
  canUseSelectedLinePairIntersection: boolean;
  canUseSelectedArcCurveCogo: boolean;
  canCreateIntersectionPoint: boolean;
  canCreateAlignment: boolean;
  canReportAlignmentStation: boolean;
  canCreateAlignmentOffset: boolean;
  canCreateAlignmentStationEquation: boolean;
  canCreateAlignmentOffsetPoint: boolean;
  canCreateAlignmentIntervalPoints: boolean;
  canCreateParcel: boolean;
  canSplitParcelByBearing: boolean;
  canSplitParcelByArea: boolean;
  canSplitParcelBySlide: boolean;
  canSplitParcelBySwing: boolean;
  canReportParcelGap: boolean;
  canReportParcelDiagnostics: boolean;
  canReportParcelOverlap: boolean;
  canSplitParcelByLine: boolean;
  canContinueCurve: boolean;
  canTrimSelection: boolean;
  canExtendSelection: boolean;
  onStartPoint: () => void;
  onStartCogoPoint: () => void;
  onStartLine: () => void;
  onStartPolyline: () => void;
  onStartTraverse: () => void;
  onStartBatchCogo: () => void;
  onStartParcelSplitBearing: () => void;
  onStartParcelSplitArea: () => void;
  onSplitParcelBySlide: () => void;
  onSplitParcelBySwing: () => void;
  onStartArc3Point: () => void;
  onStartArcStartCenterEnd: () => void;
  onStartArcCenterStartEnd: () => void;
  onStartArcStartCenterAngle: () => void;
  onStartArcCenterStartAngle: () => void;
  onStartArcStartCenterChord: () => void;
  onStartArcCenterStartChord: () => void;
  onStartArcStartEndAngle: () => void;
  onStartArcStartEndDirection: () => void;
  onStartArcStartEndRadius: () => void;
  onStartContinueCurve: () => void;
  onStartTangentCurve: () => void;
  onStartInverse: () => void;
  onStartMultiInverse: () => void;
  onStartArea: () => void;
  onStartBearingReport: () => void;
  onStartDistanceReport: () => void;
  onStartTurnedPoint: () => void;
  onStartDeflectionPoint: () => void;
  onStartPointAlongLine: () => void;
  onStartExtendLine: () => void;
  onStartOffsetPoint: () => void;
  onStartAlignmentOffsetCreate: () => void;
  onStartAlignmentStationEquation: () => void;
  onStartAlignmentOffsetPoint: () => void;
  onStartAlignmentIntervalPoints: () => void;
  onStartCurveSolver: () => void;
  onStartRadialBearing: () => void;
  onStartPointOnCurve: () => void;
  onStartSubdivideCurve: () => void;
  onStartOffsetCurve: () => void;
  onStartPiCurve: () => void;
  onStartChordBearingCurve: () => void;
  onStartReverseCurve: () => void;
  onStartCompoundCurve: () => void;
  onStartBearingBearingIntersection: () => void;
  onStartBearingDistanceIntersection: () => void;
  onStartDistanceDistanceIntersection: () => void;
  onStartLineCircleIntersection: () => void;
  onStartPerpendicularIntersection: () => void;
  onStartOffsetIntersection: () => void;
  onStartSkewIntersection: () => void;
  onStartMove: () => void;
  onStartCopy: () => void;
  onStartExtend: () => void;
  onStartTrim: () => void;
  onStartFillet: () => void;
  onCreateIntersectionPoint: () => void;
  onCreateAlignment: () => void;
  onReportAlignmentStation: () => void;
  onCreateParcel: () => void;
  onReportParcelGap: () => void;
  onReportParcelDiagnostics: () => void;
  onReportParcelOverlap: () => void;
  onSplitParcelByLine: () => void;
  onToggleParcelLayoutPanel: () => void;
  onSelectAll: () => void;
  onClearSelection: () => void;
  onErase: () => void;
  onUndo: () => void;
  onRedo: () => void;
}
