import { readFileSync, writeFileSync } from "node:fs";
import { LSAEngine } from "../src/engine/adjust";
import { buildIndustryStyleListingText } from "../src/engine/industryListing";
const input = readFileSync("tests/fixtures/camp_design_preanalysis_traverse_only.dat", "utf8");
const projectInstruments = {
  CAMP_DEFAULT: { code:'CAMP_DEFAULT', desc:'camp design preanalysis project default', edm_const:0.001, edm_ppm:1.5, hzPrecision_sec:1.414, dirPrecision_sec:1.0, azBearingPrecision_sec:1.414, vaPrecision_sec:1.0, instCentr_m:0.00075, tgtCentr_m:0.00075, vertCentr_m:0.0005, elevDiff_const_m:0.01524, elevDiff_ppm:0, gpsStd_xy:0, levStd_mmPerKm:1.5 },
  S9: { code:'S9', desc:'camp design library instrument', edm_const:0.0008, edm_ppm:1.0, hzPrecision_sec:0.707106781, dirPrecision_sec:0.5, azBearingPrecision_sec:0.707106781, vaPrecision_sec:0.5, instCentr_m:0.00075, tgtCentr_m:0.00075, vertCentr_m:0.0005, elevDiff_const_m:0.01524, elevDiff_ppm:0, gpsStd_xy:0, levStd_mmPerKm:0 },
  SX12: { code:'SX12', desc:'n/a', edm_const:0.001, edm_ppm:1.5, hzPrecision_sec:1.414, dirPrecision_sec:1.0, azBearingPrecision_sec:1.414, vaPrecision_sec:1.0, instCentr_m:0.00075, tgtCentr_m:0.00075, vertCentr_m:0.0005, elevDiff_const_m:0.01524, elevDiff_ppm:0, gpsStd_xy:0, levStd_mmPerKm:0 },
};
const result = new LSAEngine({ input, maxIterations:10, convergenceThreshold:0.01, instrumentLibrary:projectInstruments, parseOptions:{ currentInstrument:'CAMP_DEFAULT', runMode:'preanalysis', preanalysisMode:true, coordSystemMode:'grid', crsId:'CA_NAD83_CSRS_UTM_19N', coordMode:'3D', order:'EN', deltaMode:'slope', angleStationOrder:'atfromto', lonSign:'west-positive', applyCurvatureRefraction:true, verticalReduction:'curvref', refractionCoefficient:0.07, verticalDeflectionNorthSec:0, verticalDeflectionEastSec:0 } }).solve();
const listing = buildIndustryStyleListingText(result, { maxIterations:10, convergenceLimit:0.01, precisionReportingMode:'industry-standard', units:'m', listingShowCoordinates:true, listingShowObservationsResiduals:true, listingShowErrorPropagation:true, listingShowProcessingNotes:true, listingShowAzimuthsBearings:true, listingShowLostStations:true, listingSortCoordinatesBy:'input', listingSortObservationsBy:'stdResidual', listingObservationLimit:9999 }, { coordMode:'3D', order:'EN', angleUnits:'dms', angleStationOrder:'atfromto', deltaMode:'slope', refractionCoefficient:0.07 }, { solveProfile:'industry-parity', angleCenteringModel:'geometry-aware-correlated-rays', defaultSigmaCount:0, defaultSigmaByType:'', stochasticDefaultsSummary:'', rotationAngleRad:0, currentInstrumentCode:'CAMP_DEFAULT', currentInstrumentDesc:'camp design preanalysis project default', currentInstrumentLevStdMmPerKm:1.5, verticalDeflectionNorthSec:0, verticalDeflectionEastSec:0, projectInstrumentLibrary:projectInstruments });
writeFileSync('temp/camp_preanalysis_current.lst', listing, 'utf8');
