import type { AdjustmentStatisticsContext } from './adjustStatistics';

export const buildStatisticsContextForEngine = (engine: any): AdjustmentStatisticsContext => {
  return {
      observations: engine.observations,
      stations: engine.stations,
      unknowns: engine.unknowns,
      paramIndex: engine.paramIndex,
      Qxx: engine.Qxx,
      is2D: engine.is2D,
      directionOrientations: engine.directionOrientations,
      dof: engine.dof,
      seuw: engine.seuw,
      preanalysisMode: engine.preanalysisMode,
      robustMode: engine.robustMode,
      tsCorrelationEnabled: engine.tsCorrelationEnabled,
      tsCorrelationRho: engine.tsCorrelationRho,
      tsCorrelationScope: engine.tsCorrelationScope,
      localTestCritical: engine.localTestCritical,
      maxStdRes: engine.maxStdRes,
      traverseThresholds: { ...engine.traverseThresholds },
      parseState: engine.parseState,
      solveTiming: engine.solveTiming,
      logs: engine.logs,
      chiSquare: engine.chiSquare,
      statisticalSummary: engine.statisticalSummary,
      typeSummary: engine.typeSummary,
      directionSetDiagnostics: engine.directionSetDiagnostics,
      directionTargetDiagnostics: engine.directionTargetDiagnostics,
      directionRepeatabilityDiagnostics: engine.directionRepeatabilityDiagnostics,
      setupDiagnostics: engine.setupDiagnostics,
      residualDiagnostics: engine.residualDiagnostics,
      traverseDiagnostics: engine.traverseDiagnostics,
      autoSideshotDiagnostics: engine.autoSideshotDiagnostics,
      tsCorrelationDiagnostics: engine.tsCorrelationDiagnostics,
      precisionModels: engine.precisionModels,
      stationCovariances: engine.stationCovariances,
      relativePrecision: engine.relativePrecision,
      relativeCovariances: engine.relativeCovariances,
      weakGeometryDiagnostics: engine.weakGeometryDiagnostics,
      sideshots: engine.sideshots,
      clearGeometryCache: () => engine.clearGeometryCache(),
      collectActiveObservations: () => engine.collectActiveObservations(),
      correctedDistanceModel: (obs, calcDistRaw) => engine.correctedDistanceModel(obs, calcDistRaw),
      curvatureRefractionAngle: (horiz) => engine.curvatureRefractionAngle(horiz),
      effectiveDistanceForAngularObservation: (obs) =>
        engine.effectiveDistanceForAngularObservation(obs),
      effectiveStdDev: (obs) => engine.effectiveStdDev(obs),
      getAzimuth: (fromId, toId) => engine.getAzimuth(fromId, toId),
      getModeledZenith: (obs) => engine.getModeledZenith(obs),
      getObservedHorizontalDistanceIn2D: (obs) => engine.getObservedHorizontalDistanceIn2D(obs),
      gpsComponentCount: (obs) => engine.gpsComponentCount(obs),
      gpsCovariance: (obs) => engine.gpsCovariance(obs),
      gpsDisplayResidualTransform: (obs) => engine.gpsDisplayResidualTransform(obs),
      gpsModeledVector: (obs) => engine.gpsModeledVector(obs),
      gpsModeledVectorDerivatives: (obs) => engine.gpsModeledVectorDerivatives(obs),
      gpsObservedVector: (obs) => engine.gpsObservedVector(obs),
      gpsWeight: (obs) => engine.gpsWeight(obs),
      invertNormalMatrixForStats: (normal) => engine.invertNormalMatrixForStats(normal),
      sparseRowProductsSolver: engine.sparseRowProductsSolver,
      isObservationActive: (obs) => engine.isObservationActive(obs),
      measuredAngleCorrection: (at, from, to) => engine.measuredAngleCorrection(at, from, to),
      modeledAzimuth: (rawAz, atStationId, applyConvergence) =>
        engine.modeledAzimuth(rawAz, atStationId, applyConvergence),
      wrapToPi: (value) => engine.wrapToPi(value),
      applyRobustWeightFactors: (matrix, base, factors) =>
        engine.applyRobustWeightFactors(matrix, base, factors),
      applyTsCorrelationToWeightMatrix: (matrix, rowInfo) =>
        engine.applyTsCorrelationToWeightMatrix(matrix, rowInfo, true),
      applyTsCorrelationToWeightWriter: (weights, rowInfo) =>
        engine.applyTsCorrelationToWeightWriter(weights, rowInfo, true),
      captureObservationWeightingStdDevs: (observations) =>
        engine.captureObservationWeightingStdDevs(observations),
      captureRobustWeightBase: (matrix, rowInfo) => engine.captureRobustWeightBase(matrix, rowInfo),
      captureRobustWeightBaseFromStructured: (weights, rowInfo) =>
        engine.captureRobustWeightBaseFromStructured(weights, rowInfo),
      applyRobustWeightFactorsToStructured: (weights, base, factors) =>
        engine.applyRobustWeightFactorsToStructured(weights, base, factors),
      computeRobustWeightSummary: (residuals, rowInfo) =>
        engine.computeRobustWeightSummary(residuals, rowInfo),
      computeSideshotResults: () => engine.computeSideshotResults(),
      log: (message) => engine.log(message),
      tsCorrelationGroup: (obs) => engine.tsCorrelationGroup(obs),
  };
};

