import { CANADA_DATUM_OPS, parseProj4Parameters, type CrsDefinition } from './crsCatalogCore';

export const CANADA_PROVINCIAL_CATALOG_PART_1: CrsDefinition[] = [
{
    id: 'CA_NAD83_CSRS_SK_ATS',
    label: 'Saskatchewan ATS (UTM Ext 13N Alias)',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)v8',
    projectionFamily: 'transverse-mercator',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Saskatchewan',
    areaOfUseBounds: { minLatDeg: 49, maxLatDeg: 60.01, minLonDeg: -110, maxLonDeg: -101.34 },
    epsgCode: '22813',
    validityStatus: 'legacy-app-alias',
    proj4: '+proj=utm +zone=13 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=utm +zone=13 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lon0Deg: -105,
      k0: 0.9996,
      falseEastingM: 500000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_MB_3TM',
    label: 'Manitoba 3TM (MTM 17 Alias)',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'mtm',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Manitoba',
    areaOfUseBounds: { minLatDeg: 48.95, maxLatDeg: 60, minLonDeg: -102.1, maxLonDeg: -89.1 },
    validityStatus: 'legacy-app-alias',
    proj4:
      '+proj=tmerc +lat_0=0 +lon_0=-96 +k=0.9999 +x_0=304800 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=tmerc +lat_0=0 +lon_0=-96 +k=0.9999 +x_0=304800 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 0,
      lon0Deg: -96,
      k0: 0.9999,
      falseEastingM: 304800,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_NU_STEREOGRAPHIC',
    label: 'Nunavut Atlas Lambert (EPSG:3977 Alias)',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83',
    datumRealization: 'NAD83',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Nunavut',
    areaOfUseBounds: { minLatDeg: 51.62, maxLatDeg: 84, minLonDeg: -120, maxLonDeg: -60 },
    epsgCode: '3977',
    validityStatus: 'legacy-app-alias',
    proj4:
      '+proj=lcc +lat_0=49 +lon_0=-95 +lat_1=49 +lat_2=77 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=49 +lon_0=-95 +lat_1=49 +lat_2=77 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 49,
      lon0Deg: -95,
      lat1Deg: 49,
      lat2Deg: 77,
      falseEastingM: 0,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_AB_10TM_FOREST',
    label: 'Alberta 10-TM (Forest)',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'transverse-mercator',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Alberta',
    areaOfUseBounds: { minLatDeg: 48.99, maxLatDeg: 60, minLonDeg: -120, maxLonDeg: -109.98 },
    epsgCode: '3402',
    validityStatus: 'current',
    proj4:
      '+proj=tmerc +lat_0=0 +lon_0=-115 +k=0.9992 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=tmerc +lat_0=0 +lon_0=-115 +k=0.9992 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 0,
      lon0Deg: -115,
      k0: 0.9992,
      falseEastingM: 500000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_YT_ALBERS',
    label: 'Yukon Albers',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'albers-equal-area',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Yukon',
    areaOfUseBounds: { minLatDeg: 59.99, maxLatDeg: 69.7, minLonDeg: -141.01, maxLonDeg: -123.91 },
    epsgCode: '3579',
    validityStatus: 'current',
    proj4:
      '+proj=aea +lat_0=59 +lon_0=-132.5 +lat_1=61.6666666666667 +lat_2=68 +x_0=500000 +y_0=500000 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=aea +lat_0=59 +lon_0=-132.5 +lat_1=61.6666666666667 +lat_2=68 +x_0=500000 +y_0=500000 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 59,
      lon0Deg: -132.5,
      lat1Deg: 61.6666666666667,
      lat2Deg: 68,
      falseEastingM: 500000,
      falseNorthingM: 500000,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_NT_LAMBERT',
    label: 'Northwest Territories Lambert',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Northwest Territories',
    areaOfUseBounds: { minLatDeg: 59.98, maxLatDeg: 78.81, minLonDeg: -136.46, maxLonDeg: -102 },
    epsgCode: '3581',
    validityStatus: 'current',
    proj4:
      '+proj=lcc +lat_0=0 +lon_0=-112 +lat_1=62 +lat_2=70 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=0 +lon_0=-112 +lat_1=62 +lat_2=70 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 0,
      lon0Deg: -112,
      lat1Deg: 62,
      lat2Deg: 70,
      falseEastingM: 0,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_CA_ATLAS_LAMBERT',
    label: 'Canada Atlas Lambert',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Canada',
    areaOfUseBounds: { minLatDeg: 38.21, maxLatDeg: 86.46, minLonDeg: -141.01, maxLonDeg: -40.73 },
    epsgCode: '3979',
    validityStatus: 'current',
    proj4:
      '+proj=lcc +lat_0=49 +lon_0=-95 +lat_1=49 +lat_2=77 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=49 +lon_0=-95 +lat_1=49 +lat_2=77 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 49,
      lon0Deg: -95,
      lat1Deg: 49,
      lat2Deg: 77,
      falseEastingM: 0,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_ON_TERANET_LAMBERT',
    label: 'Teranet Ontario Lambert',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Ontario',
    areaOfUseBounds: { minLatDeg: 41.67, maxLatDeg: 56.9, minLonDeg: -95.16, maxLonDeg: -74.35 },
    epsgCode: '5321',
    validityStatus: 'current',
    proj4:
      '+proj=lcc +lat_0=0 +lon_0=-84 +lat_1=44.5 +lat_2=54.5 +x_0=1000000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=0 +lon_0=-84 +lat_1=44.5 +lat_2=54.5 +x_0=1000000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 0,
      lon0Deg: -84,
      lat1Deg: 44.5,
      lat2Deg: 54.5,
      falseEastingM: 1000000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_ARCTIC_LCC_3_29',
    label: 'Arctic Zone 3-29',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Canadian Arctic',
    areaOfUseBounds: { minLatDeg: 76.16, maxLatDeg: 81.17, minLonDeg: -84, maxLonDeg: -64.78 },
    epsgCode: '6103',
    validityStatus: 'current',
    proj4:
      '+proj=lcc +lat_0=78.7073375277778 +lon_0=-69 +lat_1=80.3333333333333 +lat_2=77 +x_0=29500000 +y_0=3500000 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=78.7073375277778 +lon_0=-69 +lat_1=80.3333333333333 +lat_2=77 +x_0=29500000 +y_0=3500000 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 78.7073375277778,
      lon0Deg: -69,
      lat1Deg: 80.3333333333333,
      lat2Deg: 77,
      falseEastingM: 29500000,
      falseNorthingM: 3500000,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_YT_TM',
    label: 'Yukon Territorial TM Alias',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)v8',
    projectionFamily: 'transverse-mercator',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Yukon',
    areaOfUseBounds: { minLatDeg: 59.99, maxLatDeg: 69.7, minLonDeg: -141.01, maxLonDeg: -123.8 },
    validityStatus: 'legacy-app-alias',
    proj4: '+proj=utm +zone=8 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=utm +zone=8 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lon0Deg: -135,
      k0: 0.9996,
      falseEastingM: 500000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_NT_TM',
    label: 'Northwest Territories TM Alias',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)v8',
    projectionFamily: 'transverse-mercator',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Northwest Territories',
    areaOfUseBounds: { minLatDeg: 59.99, maxLatDeg: 84, minLonDeg: -136.46, maxLonDeg: -102 },
    validityStatus: 'legacy-app-alias',
    proj4: '+proj=utm +zone=10 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=utm +zone=10 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lon0Deg: -123,
      k0: 0.9996,
      falseEastingM: 500000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_QC_MUNICIPAL_LCC',
    label: 'Quebec Municipal LCC',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)v2',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Quebec',
    areaOfUseBounds: { minLatDeg: 44.99, maxLatDeg: 62.62, minLonDeg: -79.85, maxLonDeg: -57.1 },
    epsgCode: '6622',
    validityStatus: 'current',
    proj4:
      '+proj=lcc +lat_0=44 +lon_0=-70 +lat_1=50 +lat_2=46 +x_0=800000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=44 +lon_0=-70 +lat_1=50 +lat_2=46 +x_0=800000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 44,
      lon0Deg: -70,
      lat1Deg: 50,
      lat2Deg: 46,
      falseEastingM: 800000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_QC_LAMBERT',
    label: 'Quebec MTQ Lambert',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)',
    projectionFamily: 'lambert-conformal-conic',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Quebec',
    areaOfUseBounds: { minLatDeg: 44.99, maxLatDeg: 62.62, minLonDeg: -79.85, maxLonDeg: -57.1 },
    epsgCode: '3799',
    validityStatus: 'current',
    proj4:
      '+proj=lcc +lat_0=44 +lon_0=-70 +lat_1=50 +lat_2=46 +x_0=800000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=lcc +lat_0=44 +lon_0=-70 +lat_1=50 +lat_2=46 +x_0=800000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 44,
      lon0Deg: -70,
      lat1Deg: 50,
      lat2Deg: 46,
      falseEastingM: 800000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_NS_MTM_2010_4',
    label: 'Nova Scotia MTM 2010 Zone 4',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)v6',
    projectionFamily: 'transverse-mercator',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Nova Scotia east of 63Â°W',
    areaOfUseBounds: { minLatDeg: 44.64, maxLatDeg: 47.08, minLonDeg: -63, maxLonDeg: -59.73 },
    epsgCode: '8082',
    validityStatus: 'current',
    proj4:
      '+proj=tmerc +lat_0=0 +lon_0=-61.5 +k=0.9999 +x_0=24500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=tmerc +lat_0=0 +lon_0=-61.5 +k=0.9999 +x_0=24500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 0,
      lon0Deg: -61.5,
      k0: 0.9999,
      falseEastingM: 24500000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
{
    id: 'CA_NAD83_CSRS_NS_MTM_2010_5',
    label: 'Nova Scotia MTM 2010 Zone 5',
    catalogGroup: 'canada-provincial',
    region: 'canada',
    datum: 'NAD83(CSRS)',
    datumRealization: 'NAD83(CSRS)v6',
    projectionFamily: 'transverse-mercator',
    linearUnit: 'm',
    axisOrder: 'E,N',
    areaOfUse: 'Nova Scotia west of 63Â°W',
    areaOfUseBounds: { minLatDeg: 43.41, maxLatDeg: 46.02, minLonDeg: -66.28, maxLonDeg: -63 },
    epsgCode: '8083',
    validityStatus: 'current',
    proj4:
      '+proj=tmerc +lat_0=0 +lon_0=-64.5 +k=0.9999 +x_0=25500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    projParams: parseProj4Parameters(
      '+proj=tmerc +lat_0=0 +lon_0=-64.5 +k=0.9999 +x_0=25500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs',
    ),
    projectionParams: {
      lat0Deg: 0,
      lon0Deg: -64.5,
      k0: 0.9999,
      falseEastingM: 25500000,
      falseNorthingM: 0,
    },
    supportedDatumOps: CANADA_DATUM_OPS,
  },
];
