import { DEFAULT_CANADA_CRS_ID } from './crsCatalog';
import {
  DEFAULT_QFIX_ANGULAR_SIGMA_SEC,
  DEFAULT_QFIX_LINEAR_SIGMA_M,
} from './defaults';
import type { ParseOptions } from '../types';

export const defaultParseOptions: ParseOptions = {
  geometryDependentSigmaReference: 'current',
  runMode: 'adjustment',
  units: 'm',
  coordMode: '3D',
  coordSystemMode: 'local',
  crsId: DEFAULT_CANADA_CRS_ID,
  localDatumScheme: 'average-scale',
  averageScaleFactor: 1,
  scaleOverrideActive: false,
  commonElevation: 0,
  averageGeoidHeight: 0,
  reductionContext: {
    inputSpaceDefault: 'measured',
    distanceKind: 'ground',
    bearingKind: 'grid',
    explicitOverrideActive: false,
  },
  observationMode: {
    bearing: 'grid',
    distance: 'measured',
    angle: 'measured',
    direction: 'measured',
  },
  gridBearingMode: 'grid',
  gridDistanceMode: 'measured',
  gridAngleMode: 'measured',
  gridDirectionMode: 'measured',
  preanalysisMode: false,
  order: 'EN',
  angleStationOrder: 'atfromto',
  deltaMode: 'slope',
  mapMode: 'off',
  normalize: true,
  faceNormalizationMode: 'on',
  directionFaceReliabilityFromCluster: false,
  directionFaceZenithWindowDeg: 45,
  directionFaceClusterSeparationDeg: 180,
  directionFaceClusterSeparationToleranceDeg: 20,
  directionFaceClusterConfidenceMin: 0.35,
  mapScaleFactor: 1,
  applyCurvatureRefraction: false,
  refractionCoefficient: 0.13,
  verticalReduction: 'none',
  crsTransformEnabled: false,
  crsProjectionModel: 'legacy-equirectangular',
  crsLabel: '',
  crsGridScaleEnabled: false,
  crsGridScaleFactor: 1,
  crsConvergenceEnabled: false,
  crsConvergenceAngleRad: 0,
  geoidModelEnabled: false,
  geoidModelId: 'NGS-DEMO',
  geoidSourceFormat: 'builtin',
  geoidSourcePath: '',
  geoidSourceResolvedFormat: 'builtin',
  geoidSourceFallbackUsed: false,
  geoidInterpolation: 'bilinear',
  geoidHeightConversionEnabled: false,
  geoidOutputHeightDatum: 'orthometric',
  geoidModelLoaded: false,
  geoidModelMetadata: '',
  geoidSampleUndulationM: undefined,
  geoidConvertedStationCount: 0,
  geoidSkippedStationCount: 0,
  gpsVectorMode: 'network',
  gpsWeightingMode: 'standard',
  gpsVectorFactorHorizontal: 1,
  gpsVectorFactorVertical: 1,
  gnssVectorFrameDefault: 'gridNEU',
  gnssFrameConfirmed: false,
  verticalDeflectionNorthSec: 0,
  verticalDeflectionEastSec: 0,
  gpsTopoShots: [],
  gpsAddHiHtEnabled: false,
  gpsAddHiHtHiM: 0,
  gpsAddHiHtHtM: 0,
  gpsLoopCheckEnabled: false,
  levelLoopToleranceBaseMm: 0,
  levelLoopTolerancePerSqrtKmMm: 4,
  lonSign: 'west-negative',
  currentInstrument: undefined,
  projectDefaultInstrument: undefined,
  edmMode: 'additive',
  applyCentering: true,
  addCenteringToExplicit: false,
  debug: false,
  angleMode: 'auto',
  tsCorrelationEnabled: false,
  tsCorrelationRho: 0.25,
  tsCorrelationScope: 'set',
  robustMode: 'none',
  robustK: 1.5,
  descriptionReconcileMode: 'first',
  descriptionAppendDelimiter: ' | ',
  qFixLinearSigmaM: DEFAULT_QFIX_LINEAR_SIGMA_M,
  qFixAngularSigmaSec: DEFAULT_QFIX_ANGULAR_SIGMA_SEC,
  prismEnabled: false,
  prismOffset: 0,
  prismScope: 'global',
  positionalToleranceEnabled: false,
  positionalToleranceConstantMm: 0,
  positionalTolerancePpm: 0,
  positionalToleranceConfidencePercent: 95,
  ellipseStationIds: [],
  relativeLinePairs: [],
  positionalTolerancePairs: [],
  rotationAngleRad: 0,
  lostStationIds: [],
  autoAdjustEnabled: false,
  autoAdjustMaxCycles: 3,
  autoAdjustMaxRemovalsPerCycle: 1,
  autoAdjustStdResThreshold: 4,
  autoSideshotEnabled: true,
  directionSetMode: 'reduced',
  parseCompatibilityMode: 'legacy',
  parseCompatibilityDiagnostics: [],
  ambiguousCount: 0,
  legacyFallbackCount: 0,
  strictRejectCount: 0,
  rewriteSuggestionCount: 0,
  parseModeMigrated: false,
  sourceFile: '<input>',
  includeFiles: {},
  includeMaxDepth: 16,
  includeStack: [],
  includeTrace: [],
  includeErrors: [],
  compatibilityAcceptedNoOpDirectives: [],
  stationSeparator: '-',
  dataInputEnabled: true,
  threeReduceMode: false,
  linearMultiplier: 1,
  elevationInputMode: 'orthometric',
  projectElevationMeters: 0,
  clusterDetectionEnabled: true,
  clusterLinkageMode: 'single',
  clusterTolerance2D: 0.03,
  clusterTolerance3D: 0.05,
  clusterApprovedMerges: [],
  clusterPassLabel: 'single',
  clusterDualPassRan: false,
  clusterApprovedMergeCount: 0,
  preferExternalInstruments: false,
  directiveTransitions: [],
  directiveNoEffectWarnings: [],
};

const cloneParseOptionValue = <T>(value: T): T => {
  if (Array.isArray(value) || (typeof value === 'object' && value != null)) {
    return JSON.parse(JSON.stringify(value)) as T;
  }
  return value;
};

const PROJECT_FILE_RESET_KEYS: Array<keyof ParseOptions> = [
  'geometryDependentSigmaReference',
  'runMode',
  'parseCompatibilityMode',
  'faceNormalizationMode',
  'directionFaceReliabilityFromCluster',
  'directionFaceZenithWindowDeg',
  'directionFaceClusterSeparationDeg',
  'directionFaceClusterSeparationToleranceDeg',
  'directionFaceClusterConfidenceMin',
  'parseModeMigrated',
  'units',
  'coordMode',
  'coordSystemMode',
  'crsId',
  'localDatumScheme',
  'averageScaleFactor',
  'scaleOverrideActive',
  'commonElevation',
  'averageGeoidHeight',
  'reductionContext',
  'observationMode',
  'gridBearingMode',
  'gridDistanceMode',
  'gridAngleMode',
  'gridDirectionMode',
  'preanalysisMode',
  'order',
  'angleUnits',
  'angleStationOrder',
  'deltaMode',
  'mapMode',
  'mapScaleFactor',
  'normalize',
  'applyCurvatureRefraction',
  'refractionCoefficient',
  'verticalReduction',
  'originLatDeg',
  'originLonDeg',
  'crsTransformEnabled',
  'crsProjectionModel',
  'crsLabel',
  'crsGridScaleEnabled',
  'crsGridScaleFactor',
  'crsConvergenceEnabled',
  'crsConvergenceAngleRad',
  'geoidModelEnabled',
  'geoidModelId',
  'geoidSourceFormat',
  'geoidSourcePath',
  'geoidSourceResolvedFormat',
  'geoidSourceFallbackUsed',
  'geoidInterpolation',
  'geoidHeightConversionEnabled',
  'geoidOutputHeightDatum',
  'geoidModelLoaded',
  'geoidModelMetadata',
  'geoidSampleUndulationM',
  'gpsVectorMode',
  'gpsWeightingMode',
  'gpsVectorFactorHorizontal',
  'gpsVectorFactorVertical',
  'gnssVectorFrameDefault',
  'gnssFrameConfirmed',
  'verticalDeflectionNorthSec',
  'verticalDeflectionEastSec',
  'gpsAddHiHtEnabled',
  'gpsAddHiHtHiM',
  'gpsAddHiHtHtM',
  'gpsLoopCheckEnabled',
  'levelLoopToleranceBaseMm',
  'levelLoopTolerancePerSqrtKmMm',
  'lonSign',
  'currentInstrument',
  'projectDefaultInstrument',
  'edmMode',
  'applyCentering',
  'addCenteringToExplicit',
  'debug',
  'angleMode',
  'tsCorrelationEnabled',
  'tsCorrelationRho',
  'tsCorrelationScope',
  'robustMode',
  'robustK',
  'qFixLinearSigmaM',
  'qFixAngularSigmaSec',
  'prismEnabled',
  'prismOffset',
  'prismScope',
  'positionalToleranceEnabled',
  'positionalToleranceConstantMm',
  'positionalTolerancePpm',
  'positionalToleranceConfidencePercent',
  'ellipseStationIds',
  'relativeLinePairs',
  'positionalTolerancePairs',
  'rotationAngleRad',
  'lostStationIds',
  'autoAdjustEnabled',
  'autoAdjustMaxCycles',
  'autoAdjustMaxRemovalsPerCycle',
  'autoAdjustStdResThreshold',
  'suspectImpactMode',
  'autoSideshotEnabled',
  'directionSetMode',
  'clusterDetectionEnabled',
  'clusterLinkageMode',
  'clusterTolerance2D',
  'clusterTolerance3D',
  'clusterApprovedMerges',
  'clusterPassLabel',
  'clusterDualPassRan',
  'clusterApprovedMergeCount',
  'preferExternalInstruments',
  'descriptionReconcileMode',
  'descriptionAppendDelimiter',
  'compatibilityAcceptedNoOpDirectives',
  'stationSeparator',
  'dataInputEnabled',
  'threeReduceMode',
  'linearMultiplier',
  'elevationInputMode',
  'projectElevationMeters',
];

export const buildProjectFileResetState = (state: ParseOptions): Partial<ParseOptions> =>
  Object.fromEntries(
    PROJECT_FILE_RESET_KEYS.map((key) => [key, cloneParseOptionValue(state[key])]),
  ) as Partial<ParseOptions>;

export const resetParseStateToProjectDefaults = (
  state: ParseOptions,
  defaults: Partial<ParseOptions>,
): void => {
  PROJECT_FILE_RESET_KEYS.forEach((key) => {
    ((state as unknown) as Record<string, unknown>)[key as string] = cloneParseOptionValue(
      defaults[key],
    );
  });
};
