import { useMemo } from 'react';
import type { RunDiagnostics } from '../appStateTypes';

export const useProcessingSummaryDiagnostics = (runDiagnostics: RunDiagnostics | null) =>
  useMemo(
    () =>
      runDiagnostics
        ? {
            solveProfile: runDiagnostics.solveProfile,
            directionSetMode: runDiagnostics.directionSetMode,
            profileDefaultInstrumentFallback: runDiagnostics.profileDefaultInstrumentFallback,
            rotationAngleRad: runDiagnostics.rotationAngleRad,
            coordSystemMode: runDiagnostics.coordSystemMode,
            crsId: runDiagnostics.crsId,
            localDatumScheme: runDiagnostics.localDatumScheme,
            averageScaleFactor: runDiagnostics.averageScaleFactor,
            scaleOverrideActive: runDiagnostics.scaleOverrideActive,
            commonElevation: runDiagnostics.commonElevation,
            averageGeoidHeight: runDiagnostics.averageGeoidHeight,
            gnssVectorFrameDefault: runDiagnostics.gnssVectorFrameDefault,
            gnssFrameConfirmed: runDiagnostics.gnssFrameConfirmed,
            gridBearingMode: runDiagnostics.gridBearingMode,
            gridDistanceMode: runDiagnostics.gridDistanceMode,
            gridAngleMode: runDiagnostics.gridAngleMode,
            gridDirectionMode: runDiagnostics.gridDirectionMode,
            datumSufficiencyReport: runDiagnostics.datumSufficiencyReport,
            parsedUsageSummary: runDiagnostics.parsedUsageSummary,
            usedInSolveUsageSummary: runDiagnostics.usedInSolveUsageSummary,
            directiveTransitions: runDiagnostics.directiveTransitions,
            directiveNoEffectWarnings: runDiagnostics.directiveNoEffectWarnings,
            coordSystemDiagnostics: runDiagnostics.coordSystemDiagnostics,
            coordSystemWarningMessages: runDiagnostics.coordSystemWarningMessages,
            crsStatus: runDiagnostics.crsStatus,
            crsOffReason: runDiagnostics.crsOffReason,
            crsDatumOpId: runDiagnostics.crsDatumOpId,
            crsDatumFallbackUsed: runDiagnostics.crsDatumFallbackUsed,
            crsAreaOfUseStatus: runDiagnostics.crsAreaOfUseStatus,
            crsOutOfAreaStationCount: runDiagnostics.crsOutOfAreaStationCount,
            crsGridScaleEnabled: runDiagnostics.crsGridScaleEnabled,
            crsGridScaleFactor: runDiagnostics.crsGridScaleFactor,
            crsConvergenceEnabled: runDiagnostics.crsConvergenceEnabled,
            crsConvergenceAngleRad: runDiagnostics.crsConvergenceAngleRad,
            geoidModelEnabled: runDiagnostics.geoidModelEnabled,
            geoidModelId: runDiagnostics.geoidModelId,
            geoidInterpolation: runDiagnostics.geoidInterpolation,
            geoidHeightConversionEnabled: runDiagnostics.geoidHeightConversionEnabled,
            geoidOutputHeightDatum: runDiagnostics.geoidOutputHeightDatum,
            geoidModelLoaded: runDiagnostics.geoidModelLoaded,
            geoidModelMetadata: runDiagnostics.geoidModelMetadata,
            geoidSampleUndulationM: runDiagnostics.geoidSampleUndulationM,
            geoidConvertedStationCount: runDiagnostics.geoidConvertedStationCount,
            geoidSkippedStationCount: runDiagnostics.geoidSkippedStationCount,
            gpsAddHiHtEnabled: runDiagnostics.gpsAddHiHtEnabled,
            gpsAddHiHtHiM: runDiagnostics.gpsAddHiHtHiM,
            gpsAddHiHtHtM: runDiagnostics.gpsAddHiHtHtM,
            gpsAddHiHtVectorCount: runDiagnostics.gpsAddHiHtVectorCount,
            gpsAddHiHtAppliedCount: runDiagnostics.gpsAddHiHtAppliedCount,
            gpsAddHiHtPositiveCount: runDiagnostics.gpsAddHiHtPositiveCount,
            gpsAddHiHtNegativeCount: runDiagnostics.gpsAddHiHtNegativeCount,
            gpsAddHiHtNeutralCount: runDiagnostics.gpsAddHiHtNeutralCount,
            gpsAddHiHtDefaultZeroCount: runDiagnostics.gpsAddHiHtDefaultZeroCount,
            gpsAddHiHtMissingHeightCount: runDiagnostics.gpsAddHiHtMissingHeightCount,
            gpsAddHiHtScaleMin: runDiagnostics.gpsAddHiHtScaleMin,
            gpsAddHiHtScaleMax: runDiagnostics.gpsAddHiHtScaleMax,
          }
        : null,
    [runDiagnostics],
  );
