import type {
  ParseSettings,
  SettingsState,
} from '../appStateTypes';
import type {
  RunMode,
} from '../types';
import { resolveProjectOptionsModalStaticContext } from './useProjectOptionsModalStaticContext';
import type {
  ProjectOptionsModalStaticContext,
  UseProjectOptionsModalControllerArgs,
} from './useProjectOptionsModalController.types';
import { useProjectOptionsAdjustedPointsController } from './useProjectOptionsAdjustedPointsController';
import { useProjectOptionsDraftSettingsController } from './useProjectOptionsDraftSettingsController';
import { useProjectOptionsInstrumentController } from './useProjectOptionsInstrumentController';
import { useProjectOptionsLevelLoopController } from './useProjectOptionsLevelLoopController';

export const useProjectOptionsModalController = ({
  projectOptionsState,
  adjustedPointsDraftStationIds,
  adjustedPointsTransformDraftValidationMessage,
  crsCatalogGroupCounts,
  filteredDraftCrsCatalog,
  searchedDraftCrsCatalog,
  visibleDraftCrsCatalog,
  selectedDraftCrs,
  selectedCrsProj4Params,
  exportFormat,
  setExportFormat,
  storageStatus = null,
  recentProjects = [],
  projectSession = null,
  activeProjectFileViews = [],
  currentProjectFile = null,
  handleSaveProject,
  triggerProjectFileSelect,
  triggerProjectSourceFileSelect = () => undefined,
  createLocalProjectFromCurrentWorkspace = () => undefined,
  openProjectById = () => undefined,
  deleteLocalProject = () => undefined,
  exportPortableProject = () => undefined,
  exportProjectBundle = () => undefined,
  createBlankProjectFile = () => undefined,
  switchActiveProjectFile = () => undefined,
  renameProjectFile = () => undefined,
  toggleProjectFileEnabled = () => undefined,
  moveProjectFile = () => undefined,
  removeProjectFile = () => undefined,
  geoidSourceFileInputRef,
  settingsModalContentRef,
  adjustedPointsDragRef,
  runDiagnostics,
  normalizeSolveProfile,
  normalizeUiTheme,
  buildObservationModeFromGridFields,
  createInstrument,
  createCustomLevelLoopTolerancePreset,
  resolveLevelLoopTolerancePreset,
  staticContext,
}: UseProjectOptionsModalControllerArgs) => {
  const resolvedStaticContext: ProjectOptionsModalStaticContext =
    resolveProjectOptionsModalStaticContext(staticContext, normalizeUiTheme);

  const {
    isSettingsModalOpen,
    activeOptionsTab,
    setActiveOptionsTab,
    settingsDraft,
    setSettingsDraft,
    parseSettingsDraft,
    setParseSettingsDraft,
    geoidSourceDataDraft,
    setGeoidSourceDataDraft,
    geoidSourceDataLabelDraft,
    setGeoidSourceDataLabelDraft,
    crsCatalogGroupFilter,
    setCrsCatalogGroupFilter,
    crsSearchQuery,
    setCrsSearchQuery,
    showCrsProjectionParams,
    setShowCrsProjectionParams,
    projectInstrumentsDraft,
    setProjectInstrumentsDraft,
    levelLoopCustomPresetsDraft,
    setLevelLoopCustomPresetsDraft,
    adjustedPointsExportSettingsDraft,
    setAdjustedPointsExportSettingsDraft,
    adjustedPointsTransformSelectedDraft,
    setAdjustedPointsTransformSelectedDraft,
    adjustedPointsRotationAngleInput,
    setAdjustedPointsRotationAngleInput,
    adjustedPointsTranslationAzimuthInput,
    setAdjustedPointsTranslationAzimuthInput,
    adjustedPointsRotationAngleError,
    setAdjustedPointsRotationAngleError,
    adjustedPointsTranslationAzimuthError,
    setAdjustedPointsTranslationAzimuthError,
    selectedInstrumentDraft,
    setSelectedInstrumentDraft,
    closeProjectOptions,
    applyProjectOptions,
  } = projectOptionsState;

  const {
    clearDraftGeoidSourceData,
    handleDraftConvergenceLimitChange,
    handleDraftIterChange,
    handleDraftParseSetting,
    handleDraftUnitChange,
    handleGeoidSourceFileChange,
    handleGeoidSourceFilePick,
    migrateDraftParseModeToStrict,
  } = useProjectOptionsDraftSettingsController({
    buildObservationModeFromGridFields,
    geoidSourceFileInputRef,
    normalizeSolveProfile,
    parseSettingsDraft,
    setGeoidSourceDataDraft,
    setGeoidSourceDataLabelDraft,
    setParseSettingsDraft,
    setSettingsDraft,
  });

  const {
    applyAdjustedPointsTransformSelection,
    closeAdjustedPointsTransformSelectModal,
    handleAdjustedPointsDragStart,
    handleAdjustedPointsDrop,
    handleAdjustedPointsMoveColumn,
    handleAdjustedPointsPresetChange,
    handleAdjustedPointsToggleColumn,
    handleAdjustedPointsTransformToggleSelected,
    handleDraftAdjustedPointsRotationAngleInput,
    handleDraftAdjustedPointsRotationSetting,
    handleDraftAdjustedPointsScaleSetting,
    handleDraftAdjustedPointsSetting,
    handleDraftAdjustedPointsTransformSetting,
    handleDraftAdjustedPointsTranslationAzimuthInput,
    handleDraftAdjustedPointsTranslationSetting,
    openAdjustedPointsTransformSelectModal,
  } = useProjectOptionsAdjustedPointsController({
    adjustedPointsDraftStationIds,
    adjustedPointsDragRef,
    adjustedPointsExportSettingsDraft,
    adjustedPointsRotationAngleError,
    adjustedPointsTranslationAzimuthError,
    adjustedPointsTransformSelectedDraft,
    projectOptionsState,
    setAdjustedPointsExportSettingsDraft,
    setAdjustedPointsRotationAngleError,
    setAdjustedPointsRotationAngleInput,
    setAdjustedPointsTransformSelectedDraft,
    setAdjustedPointsTranslationAzimuthError,
    setAdjustedPointsTranslationAzimuthInput,
  });

  const {
    activeLevelLoopPreset,
    activeLevelLoopPresetId,
    addLevelLoopCustomPreset,
    handleLevelLoopCustomPresetFieldChange,
    handleLevelLoopPresetChange,
    removeLevelLoopCustomPreset,
  } = useProjectOptionsLevelLoopController({
    createCustomLevelLoopTolerancePreset,
    levelLoopCustomPresetsDraft,
    parseSettingsDraft,
    resolveLevelLoopTolerancePreset,
    setLevelLoopCustomPresetsDraft,
    setParseSettingsDraft,
  });

  const handleDraftSetting = <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => {
    setSettingsDraft((prev) => ({ ...prev, [key]: value }));
  };

  const {
    addNewInstrument,
    displayLinear,
    duplicateSelectedInstrument,
    handleInstrumentFieldChange,
    handleInstrumentLinearFieldChange,
    handleInstrumentNumericFieldChange,
    instrumentLinearUnit,
    selectedInstrumentMeta,
  } = useProjectOptionsInstrumentController({
    createInstrument,
    projectInstrumentsDraft,
    resolvedStaticContext,
    selectedInstrumentDraft,
    setProjectInstrumentsDraft,
    setSelectedInstrumentDraft,
    settingsDraft,
  });

  const parityProfileActive = true;
  const adjustedPointsTransformSelectedInSetCount = adjustedPointsExportSettingsDraft.transform.selectedStationIds.filter(
    (id) => adjustedPointsDraftStationIds.includes(id),
  ).length;

  const projectOptionsModalContext = {
    ...resolvedStaticContext,
    activeLevelLoopPreset,
    activeLevelLoopPresetId,
    activeOptionsTab,
    addLevelLoopCustomPreset,
    addNewInstrument,
    adjustedPointsDraftStationIds,
    adjustedPointsExportSettingsDraft,
    adjustedPointsRotationAngleError,
    adjustedPointsRotationAngleInput,
    adjustedPointsTransformDraftValidationMessage,
    adjustedPointsTransformSelectedInSetCount,
    adjustedPointsTranslationAzimuthError,
    adjustedPointsTranslationAzimuthInput,
    applyAdjustedPointsTransformSelection,
    applyProjectOptions,
    clearDraftGeoidSourceData,
    closeProjectOptions,
    crsCatalogGroupCounts,
    crsCatalogGroupFilter,
    crsSearchQuery,
    displayLinear,
    duplicateSelectedInstrument,
    exportFormat,
    storageStatus,
    recentProjects,
    projectSession,
    activeProjectFileViews,
    currentProjectFile,
    filteredDraftCrsCatalog,
    geoidSourceDataDraft,
    geoidSourceDataLabelDraft,
    geoidSourceFileInputRef,
    handleAdjustedPointsDragStart,
    handleAdjustedPointsDrop,
    handleAdjustedPointsMoveColumn,
    handleAdjustedPointsPresetChange,
    handleAdjustedPointsToggleColumn,
    handleAdjustedPointsTransformToggleSelected,
    handleDraftAdjustedPointsRotationAngleInput,
    handleDraftAdjustedPointsRotationSetting,
    handleDraftAdjustedPointsScaleSetting,
    handleDraftAdjustedPointsSetting,
    handleDraftAdjustedPointsTransformSetting,
    handleDraftAdjustedPointsTranslationAzimuthInput,
    handleDraftAdjustedPointsTranslationSetting,
    handleDraftConvergenceLimitChange,
    handleDraftIterChange,
    handleDraftParseSetting,
    handleDraftSetting,
    handleDraftUnitChange,
    handleGeoidSourceFileChange,
    handleGeoidSourceFilePick,
    handleInstrumentFieldChange,
    handleInstrumentLinearFieldChange,
    handleInstrumentNumericFieldChange,
    handleLevelLoopCustomPresetFieldChange,
    handleLevelLoopPresetChange,
    handleSaveProject,
    triggerProjectSourceFileSelect,
    createLocalProjectFromCurrentWorkspace,
    openProjectById,
    deleteLocalProject,
    exportPortableProject,
    exportProjectBundle,
    createBlankProjectFile,
    switchActiveProjectFile,
    renameProjectFile,
    toggleProjectFileEnabled,
    moveProjectFile,
    removeProjectFile,
    instrumentLinearUnit,
    isSettingsModalOpen,
    levelLoopCustomPresetsDraft,
    migrateDraftParseModeToStrict,
    normalizeSolveProfile,
    normalizeUiTheme,
    openAdjustedPointsTransformSelectModal,
    parityProfileActive,
    parseSettingsDraft,
    projectInstrumentsDraft,
    removeLevelLoopCustomPreset,
    runDiagnostics,
    searchedDraftCrsCatalog,
    selectedCrsProj4Params,
    selectedDraftCrs,
    selectedInstrumentDraft,
    selectedInstrumentMeta,
    setActiveOptionsTab,
    setCrsCatalogGroupFilter,
    setCrsSearchQuery,
    setExportFormat,
    setSelectedInstrumentDraft,
    setShowCrsProjectionParams,
    settingsDraft,
    settingsModalContentRef,
    showCrsProjectionParams,
    triggerProjectFileSelect,
    visibleDraftCrsCatalog,
  };

  return {
    applyAdjustedPointsTransformSelection,
    closeAdjustedPointsTransformSelectModal,
    handleAdjustedPointsTransformToggleSelected,
    projectOptionsModalContext,
  };
};

export type ProjectOptionsModalContext = ReturnType<
  typeof useProjectOptionsModalController
>['projectOptionsModalContext'];
