import React from 'react';
import { EXPORT_FORMAT_OPTIONS } from '../../../../engine/exportFormats';
import type { ProjectOptionsModalContext } from '../../../../hooks/useProjectOptionsModalController';
import type { ProjectExportFormat } from '../../../../types';

type OtherFileOutputsCardProps = {
  context: ProjectOptionsModalContext;
};

const OtherFileOutputsCard: React.FC<OtherFileOutputsCardProps> = ({ context }) => {
  const {
    PROJECT_OPTION_SECTION_TOOLTIPS,
    SETTINGS_TOOLTIPS,
    SettingsCard,
    SettingsRow,
    exportFormat,
    getExportFormatExtension,
    getExportFormatLabel,
    getExportFormatTooltip,
    optionInputClass,
    setExportFormat,
  } = context;

  return (
    <SettingsCard
      title="Other File Outputs"
      tooltip={PROJECT_OPTION_SECTION_TOOLTIPS['Other File Outputs']}
    >
      <SettingsRow label="Export Format" tooltip={SETTINGS_TOOLTIPS.exportFormat}>
        <select
          title={getExportFormatTooltip(exportFormat)}
          value={exportFormat}
          onChange={(e) => setExportFormat(e.target.value as ProjectExportFormat)}
          className={optionInputClass}
        >
          {EXPORT_FORMAT_OPTIONS.map((option) => (
            <option key={option.value} value={option.value}>
              {option.optionLabel}
            </option>
          ))}
        </select>
      </SettingsRow>
      <SettingsRow
        label="Output Extension"
        tooltip="Current file extension used by the active export format."
      >
        <div className="rounded border border-slate-500 bg-slate-700 px-2 py-1 text-xs text-slate-100">
          {getExportFormatExtension(exportFormat)}
        </div>
      </SettingsRow>
      <SettingsRow
        label="Output Family"
        tooltip="Describes the current export target generated by the toolbar export action."
      >
        <div className="rounded border border-slate-500 bg-slate-700 px-2 py-1 text-xs text-slate-100">
          {getExportFormatLabel(exportFormat)}
        </div>
      </SettingsRow>
      <SettingsRow
        label="Export Details"
        tooltip="Detailed description for the currently selected export target."
      >
        <div
          title={getExportFormatTooltip(exportFormat)}
          className="rounded border border-slate-500 bg-slate-700 px-2 py-1 text-xs text-slate-100"
        >
          {getExportFormatTooltip(exportFormat)}
        </div>
      </SettingsRow>
    </SettingsCard>
  );
};

export default OtherFileOutputsCard;
