// Exam Prep — current curriculum binding.
//
// ONE helper imports the bundled, frozen curriculum manifest. Every
// persistent Exam Prep record binds `curriculumId` + `curriculumContentHash`
// from this module so current selectors filter by both fields and archived
// same-curriculum/different-hash state is preserved but ignored. The manifest
// JSON itself is immutable and is never regenerated by this feature.

import examCurriculumManifestJson from '../../../study-content/exam-curriculum/nb-sit-exam-curriculum-v1.json';
import type { ExamCurriculumManifest } from '../examCurriculum/examCurriculumTypes';
import type { ExamPrepCurriculumBinding } from './examPrepTypes';

export const EXAM_PREP_MANIFEST = examCurriculumManifestJson as unknown as ExamCurriculumManifest;

export const EXAM_PREP_CURRICULUM_ID = EXAM_PREP_MANIFEST.curriculumId;
export const EXAM_PREP_CURRICULUM_CONTENT_HASH = EXAM_PREP_MANIFEST.contentHash;
export const EXAM_PREP_SOURCE_PACKAGE_ID = EXAM_PREP_MANIFEST.sourcePackageId;
export const EXAM_PREP_SOURCE_CORPUS_CONTENT_HASH = EXAM_PREP_MANIFEST.sourceCorpusContentHash;

/** Canonical current binding used by every persisted Exam Prep record. */
export const currentExamPrepBinding = (): ExamPrepCurriculumBinding => ({
  curriculumId: EXAM_PREP_CURRICULUM_ID,
  curriculumContentHash: EXAM_PREP_CURRICULUM_CONTENT_HASH,
});

export const isCurrentExamPrepBinding = (binding: ExamPrepCurriculumBinding): boolean =>
  binding.curriculumId === EXAM_PREP_CURRICULUM_ID &&
  binding.curriculumContentHash === EXAM_PREP_CURRICULUM_CONTENT_HASH;

export const isSameCurriculumOtherHash = (
  binding: ExamPrepCurriculumBinding,
): boolean =>
  binding.curriculumId === EXAM_PREP_CURRICULUM_ID &&
  binding.curriculumContentHash !== EXAM_PREP_CURRICULUM_CONTENT_HASH;

/** Composite record id: `${hash}::${localId}` for unit/task progress. */
export const examPrepProgressId = (
  binding: ExamPrepCurriculumBinding,
  localId: string,
): string => `${binding.curriculumContentHash}::${localId}`;
