import type { MapViewContentProps } from './MapViewContent';
import {
  buildContextMenuProps,
  buildScene3dProps,
  buildSvg2dProps,
  buildToolOverlayProps,
} from './MapViewRoot.props';
import { useMapView2dRenderState } from './useMapView2dRenderState';
import { useMapView3dProjection } from './useMapView3dProjection';
import { useMapViewSelectionInteractions } from './useMapViewSelectionInteractions';
import type { UseMapViewContentPropsArgs } from './useMapViewContentProps.types';

export const useMapViewContentProps = ({
  basemapDescriptorView2d,
  beginDrag,
  bbox,
  camera3d,
  clearDraftBlockedPolygon,
  clearMapSelection,
  closeContextMenu,
  commitDraftBlockedPolygon,
  contextMenu,
  derivedResult,
  derivedView2d,
  dragRef,
  draftBlockedPolygon,
  draftBlockedPolygonLength,
  effectiveMode,
  ellipseStroke,
  fallbackReason,
  focusSelection,
  hideMinorGeometry,
  handleMouseDown,
  handleMouseUp,
  handleWheel,
  idlePrefetchReady,
  inputPointsLoaded,
  interactionPhase,
  isDragging,
  isPreanalysis,
  layerRenderer,
  mode,
  obstacleFetchSignatureRef,
  observations,
  onLoadInputPoints,
  onPlanningMapChange,
  onSelectObservation,
  onSelectStation,
  planningMap,
  planningVertexDragRef,
  points,
  project2d,
  projection2d,
  removePlanningPolygon,
  removeSelectedPlanningPolygons,
  renderSurfaceLayout,
  renderer2d,
  result,
  scene3d,
  selectedObservationId,
  selectedPlanningPolygonIds,
  selectedStationId,
  selectionBox,
  setBasemapDescriptorView2d,
  setCamera3d,
  setContextMenu,
  setDraftBlockedPolygon,
  setFocusSelection,
  setHideMinorGeometry,
  setSelectedPlanningPolygonIds,
  setSelectionBox,
  setShowLabels,
  setShowTransformedCoordinates,
  showLabels,
  showLostStations,
  showTransformToggle,
  stationFill,
  stationSeverity,
  stations,
  svgToMapCoords,
  tileStoreRef,
  toSvgCoords,
  transformedLines2d,
  transformedOverlayActive,
  transformedOverlayConfig,
  transformedPoints2d,
  unitScale,
  units,
  updatePlanningPolygonVertices: _updatePlanningPolygonVertices,
  view2d,
  visibleStationRows,
  webglEligible,
  ...refsAndToolState
}: UseMapViewContentPropsArgs): MapViewContentProps => {
  const map2dRenderState = useMapView2dRenderState({
    bbox,
    basemapDescriptorView2d,
    derivedResult,
    derivedView2d,
    dragRef,
    draftBlockedPolygon,
    effectiveMode,
    ellipseStroke,
    focusSelection,
    hideMinorGeometry,
    idlePrefetchReady,
    interactionPhase,
    layerRenderer,
    obstacleFetchSignatureRef,
    observations,
    onPlanningMapChange,
    planningMap,
    points,
    project2d,
    projection2d,
    renderer2d,
    result,
    scheduleLayerRender: layerRenderer.scheduleLayerRender,
    selectedObservationId,
    selectedPlanningPolygonIds,
    selectedStationId,
    setBasemapDescriptorView2d,
    showLabels,
    showLostStations,
    stationFill,
    stationSeverity,
    stations,
    tileStoreRef,
    transformedOverlayActive,
    units,
    view2d,
  });

  const {
    filteredVisibleMapLines2d,
    filteredVisiblePoints2d,
    findPlanningPolygonAtSvgPoint,
    labelFont2d,
    labelOffset2d,
    labelStroke2d,
    lineWidth2d,
    mapDensitySummary,
    mapHitIndex2d,
    mapLinkByPairKey,
    marker2d,
    originalGeometryOpacity,
    planningPolygons2d,
    pointRadius2d,
    selectedObservationPairKey,
    svgBracePreviewPoints2d,
    svgPlanningInputPoints2d,
    svgPlanningPolygons2d,
    svgScenarioPreviewSegments2d,
    svgVisiblePointLabels2d,
  } = map2dRenderState;

  const {
    handleDeletePlanningPolygon,
    handleEditPlanningPolygon,
    handlePlanningVertexMouseDown,
    handleRemoveSelectedPlanningPolygons,
    handleSvgClick,
    openContextMenu,
    selectionBoxRect,
  } = useMapViewSelectionInteractions({
    applyPickedToolStation: refsAndToolState.applyPickedToolStation,
    beginDrag,
    clearMapSelection,
    closeContextMenu,
    containerRef: refsAndToolState.containerRef,
    contextMenu,
    effectiveMode,
    findPlanningPolygonAtSvgPoint,
    mapHitIndex2d,
    onSelectObservation,
    onSelectStation,
    planningMap,
    planningPolygons2d,
    planningVertexDragRef,
    removePlanningPolygon,
    removeSelectedPlanningPolygons,
    selectedObservationId,
    selectedPlanningPolygonIds,
    selectedStationId,
    selectionBox,
    setContextMenu,
    setDraftBlockedPolygon,
    setSelectedPlanningPolygonIds,
    setSelectionBox,
    svgToMapCoords,
    toSvgCoords,
    toolPickTarget: refsAndToolState.toolPickTarget,
    view2d,
  });

  const { applyCubeView, project3d, projected3d, projected3dById, visiblePointLabels3d } =
    useMapView3dProjection({
      camera3d,
      effectiveMode,
      scene3d,
      selectedStationId,
      setCamera3d,
    });

  const svg2dProps = buildSvg2dProps({
    bracePreviewPoints2d: svgBracePreviewPoints2d,
    filteredVisibleMapLines2d,
    filteredVisiblePoints2d,
    handlePlanningVertexMouseDown,
    highlightedToolSegments: refsAndToolState.highlightedToolSegments,
    highlightedToolStationIds: refsAndToolState.highlightedToolStationIds,
    interactionPhase,
    labelFont2d,
    labelOffset2d,
    labelStroke2d,
    lineWidth2d,
    marker2d,
    onSelectObservation,
    originalGeometryOpacity,
    planningInputPoints2d: svgPlanningInputPoints2d,
    planningPolygons2d: svgPlanningPolygons2d,
    pointRadius2d,
    project2d,
    renderer2d,
    scenarioPreviewSegments2d: svgScenarioPreviewSegments2d,
    selectedObservationId,
    selectedObservationPairKey,
    selectedPlanningPolygonIds,
    selectedStationId,
    selectionBoxRect,
    showLabels,
    transformedLines2d,
    transformedOverlayActive,
    transformedPoints2d,
    view2d,
    visiblePointLabels2d: svgVisiblePointLabels2d,
  });

  const scene3dProps = buildScene3dProps({
    camera3d,
    ellipseStroke,
    highlightedToolSegments: refsAndToolState.highlightedToolSegments,
    highlightedToolStationIds: refsAndToolState.highlightedToolStationIds,
    mapLinkByPairKey,
    onSelectObservation,
    onSelectStation,
    project3d,
    projected3d,
    projected3dById,
    scene3d,
    selectedObservationId,
    selectedObservationPairKey,
    selectedStationId,
    stationFill,
    visiblePointLabels3d,
  });

  return {
    activeTool: refsAndToolState.activeTool,
    applyCubeView,
    canShowInputPointHint: points.length === 0,
    contextMenuOpen: contextMenu.open,
    contextMenuProps: buildContextMenuProps({
      contextMenu,
      handleDeletePlanningPolygon,
      handleEditPlanningPolygon,
      handleRemoveSelectedPlanningPolygons,
      openTool: refsAndToolState.openTool,
      selectedPlanningPolygonIds,
    }),
    derivedView2d,
    effectiveMode,
    fallbackReason,
    filteredVisiblePointCount: filteredVisiblePoints2d.length,
    focusSelection,
    handleMouseDown,
    handleMouseUp,
    handleSvgClick,
    handleWheel,
    hideMinorGeometry,
    inputPointsLoaded,
    interactionPhase,
    isDragging,
    isPreanalysis,
    mapDensitySummary,
    mode,
    onLoadInputPoints,
    onPlanningMapChange,
    openContextMenu,
    planningMap,
    renderSurfaceLayout,
    renderer2d,
    scene3dProps,
    selectedPlanningPolygonIds,
    setFocusSelection,
    setHideMinorGeometry,
    setShowLabels,
    setShowTransformedCoordinates,
    showLabels,
    showTransformToggle,
    svg2dProps,
    toolOverlayProps: buildToolOverlayProps({
      activeTool: refsAndToolState.activeTool,
      angleBetween: refsAndToolState.angleBetween,
      angleFromId: refsAndToolState.angleFromId,
      angleFromInput: refsAndToolState.angleFromInput,
      anglePivotId: refsAndToolState.anglePivotId,
      anglePivotInput: refsAndToolState.anglePivotInput,
      angleToId: refsAndToolState.angleToId,
      angleToInput: refsAndToolState.angleToInput,
      closeTool: refsAndToolState.closeTool,
      inverse: refsAndToolState.inverse,
      inverseFromId: refsAndToolState.inverseFromId,
      inverseFromInput: refsAndToolState.inverseFromInput,
      inverseToId: refsAndToolState.inverseToId,
      inverseToInput: refsAndToolState.inverseToInput,
      isPreanalysis,
      setAngleFromInput: refsAndToolState.setAngleFromInput,
      setAnglePivotInput: refsAndToolState.setAnglePivotInput,
      setAngleToInput: refsAndToolState.setAngleToInput,
      setInverseFromInput: refsAndToolState.setInverseFromInput,
      setInverseToInput: refsAndToolState.setInverseToInput,
      toggleToolPickTarget: refsAndToolState.toggleToolPickTarget,
      toolPickTarget: refsAndToolState.toolPickTarget,
      unitScale,
      units,
      visibleStationRows,
    }),
    toolPickTarget: refsAndToolState.toolPickTarget,
    transformedOverlayActive,
    transformedOverlayConfig,
    unitScale,
    units,
    view2d,
    webglEligible,
    clearDraftBlockedPolygon,
    commitDraftBlockedPolygon,
    draftBlockedPolygonLength,
    removePlanningPolygon,
    removeSelectedPlanningPolygons,
    basemapCanvasRef: refsAndToolState.basemapCanvasRef,
    containerRef: refsAndToolState.containerRef,
    contextMenuRef: refsAndToolState.contextMenuRef,
    geometryCanvasRef: refsAndToolState.geometryCanvasRef,
    planningCanvasRef: refsAndToolState.planningCanvasRef,
    renderSurfaceRef: refsAndToolState.renderSurfaceRef,
    svgRef: refsAndToolState.svgRef,
    webglCanvasRef: refsAndToolState.webglCanvasRef,
  };
};
