export interface WebNetWasmModule {
  HEAPF64: Float64Array;
  HEAPU8: Uint8Array;
  HEAP32: Int32Array;
  _malloc(_size: number): number;
  _free(_pointer: number): void;
  _webnet_dense_solve(
    _normal: number,
    _rhs: number,
    _correction: number,
    _dimension: number,
    _damping: number,
    _attempts: number,
    _error: number,
    _errorCapacity: number,
  ): number;
  _webnet_sparse_equation_solve(
    _rowOffsets: number,
    _designColumns: number,
    _designValues: number,
    _designNnz: number,
    _weightRows: number,
    _weightColumns: number,
    _weightValues: number,
    _weightNnz: number,
    _misclosures: number,
    _equationCount: number,
    _parameterCount: number,
    _correction: number,
    _designNnzOut: number,
    _weightNnzOut: number,
    _normalNnzOut: number,
    _factorNnzOut: number,
    _dampingOut: number,
    _attemptsOut: number,
    _error: number,
    _errorCapacity: number,
  ): number;
  _webnet_sparse_selected_covariance(
    _rowOffsets: number,
    _designColumns: number,
    _designValues: number,
    _designNnz: number,
    _weightRows: number,
    _weightColumns: number,
    _weightValues: number,
    _weightNnz: number,
    _equationCount: number,
    _parameterCount: number,
    _queryRows: number,
    _queryColumns: number,
    _queryCount: number,
    _covarianceOut: number,
    _normalNnzOut: number,
    _factorNnzOut: number,
    _dampingOut: number,
    _attemptsOut: number,
    _error: number,
    _errorCapacity: number,
  ): number;
  _webnet_sparse_row_products(
    _rowOffsets: number,
    _designColumns: number,
    _designValues: number,
    _designNnz: number,
    _weightRows: number,
    _weightColumns: number,
    _weightValues: number,
    _weightNnz: number,
    _equationCount: number,
    _parameterCount: number,
    _queryRowOffsets: number,
    _queryColumns: number,
    _queryValues: number,
    _queryNnz: number,
    _queryRowCount: number,
    _crossA: number,
    _crossB: number,
    _crossCount: number,
    _quadraticOut: number,
    _crossOut: number,
    _normalNnzOut: number,
    _factorNnzOut: number,
    _dampingOut: number,
    _attemptsOut: number,
    _error: number,
    _errorCapacity: number,
  ): number;
}

export type WebNetWasmFactory = () => Promise<WebNetWasmModule> | WebNetWasmModule;
