/**
 * Phase 20M — grading-transition feasibility study core (STUDY ONLY).
 *
 * Pure-math illustration over hand-picked SYNTHETIC terminal daylight points
 * P1, P2. Every fixture below is an assumed-valid study shape: coordinates
 * were chosen by hand for geometric coverage, NONE were generated by a
 * production solver, and none are production evidence. Corpus rows carry
 * `synthetic: true` so they cannot be mistaken for solver output.
 * It builds NO production geometry and wires nowhere.
 *
 * Imported authorities (never copied):
 * - `zeroDelta` (surfaces/volume/zero) — scalar classification floor only.
 * - `coordinateAgreementTol` / `elevationAgreementTol` (gradingGroupSectors)
 *   — components of a STUDY agreement control. If P1≈P2 under this control
 *   the row is a study tie-control and needs no transition. This control
 *   does NOT reproduce the production exact-common-tie gate, which
 *   additionally depends on anchored leverage/gradient/FLOOR context that
 *   the study does not (and must not) reconstruct. Neighboring production
 *   20J/20K suites are the proof that actual common-tie behavior is
 *   unchanged.
 *
 * Candidate families (conceptual only):
 * - T0: direct segment P1→P2. Always geometrically constructible when both
 *   endpoints are finite; interior points differ from both terminals
 *   whenever the terminals disagree.
 * - T1: finite source-station blend of width w. Two SYNTHETIC probe widths
 *   (wA = memberLength/8, wB = 3*memberLength/8 — explicitly chosen
 *   dimensionless fractions, PROBES not defaults) are evaluated to show
 *   that two study-chosen widths yield materially different illustrative
 *   geometry. No existing authority selects between them.
 * - T2: strip/fan under an explicit new transition criterion. The study
 *   records that such a criterion does not exist in persistence/UI; no
 *   production type is introduced here.
 *
 * What this harness does NOT do: it does NOT compute production criterion
 * residuals. The `midpointGap*Illustration` columns are endpoint-gap
 * illustrations (half the terminal disagreement on the parameter-free
 * connector), not evaluated worker/engine residuals. The policy conclusion
 * rests on production forensics (worker agreement would reject interiors
 * against either member law; see decision §6/§8), not on these numbers.
 *
 * No study constant acts as policy: there are no noise floors, width
 * floors, or area quanta in this file. The only comparisons are exact
 * deterministic ones (probe widths differ by construction; illustration
 * values compared with !==).
 *
 * Determinism: fixtures sorted by id, floats rounded to 12 decimals,
 * JSON serialized with sorted keys. No timestamps, no randomness.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { zeroDelta } from '../src/engine/cad/surfaces/volume/zero';
import {
  coordinateAgreementTol,
  elevationAgreementTol,
} from '../src/engine/cad/grading/gradingGroupSectors';

export type TransitionClass =
  | 'analytic-d-mismatch'
  | 'same-d-diff-z'
  | 'sloped-disagree'
  | 'joint-z-step'
  | 'surface-analytic'
  | 'surface-surface'
  | 'root-ambiguity'
  | 'line-arc'
  | 'arc-arc'
  | 'closed-route'
  | 'exact-tie-control';

/** Study verdict vocabulary: only classifications evidenced by the corpus. */
export type Verdict =
  | 'EXACT_COMMON_TIE_CONTROL'
  | 'TRANSITION_REQUIRES_NEW_CRITERION'
  | 'TRANSITION_WIDTH_UNDERDETERMINED'
  | 'ROOT_POLICY_REQUIRED'
  | 'EXTENSION_POLICY_REQUIRED'
  | 'ARC_PAIR_NO_GO'
  | 'CLOSED_ROUTE_POLICY_REQUIRED';

export interface TransitionFixture {
  id: string;
  incompatibilityClass: TransitionClass;
  /** Synthetic terminal daylight points, assumed valid for study geometry. */
  p1: [number, number, number];
  p2: [number, number, number];
  memberLength: number;
  maxSearchDistance: number;
  roots: 0 | 1 | 2;
  extensionNeeded: boolean;
  closed: boolean;
  spanKind: 'line-line' | 'line-arc' | 'arc-line' | 'arc-arc';
  note: string;
}

export interface TransitionRow {
  fixtureId: string;
  /** Always true: no row derives from production solver output. */
  synthetic: true;
  incompatibilityClass: TransitionClass;
  candidate: 'T0' | 'T1';
  deltaPlan: number;
  deltaZ: number;
  /** Study agreement control outcome (control only, not the production gate). */
  studyAgreementTie: boolean;
  connectorLength: number;
  /** Endpoint-gap illustrations, NOT production criterion residuals. */
  midpointGapPlanIllustration: number;
  midpointGapZIllustration: number;
  widthA: number | null;
  widthB: number | null;
  areaA: number | null;
  areaB: number | null;
  zVolA: number | null;
  zVolB: number | null;
  widthUnderdetermined: boolean;
  requiresNewCriterion: boolean;
  transformMaxDev: number;
  mirrorStable: boolean;
  classification: Verdict;
  reasonCode: string;
}

const r12 = (v: number): number => {
  if (!Number.isFinite(v)) return v;
  const r = Number(v.toPrecision(12));
  return r === 0 ? 0 : r;
};

/** Local-frame shift: subtract origin before measuring (avoids 1e8 artifacts). */
const local = (p: readonly number[], origin: readonly number[]): [number, number, number] => [
  p[0]! - origin[0]!,
  p[1]! - origin[1]!,
  p[2]! - origin[2]!,
];

/**
 * All fixtures are hand-picked synthetic coordinates assumed valid for study
 * geometry. Notes saying "inspired by" name the production shape they mimic;
 * they are analogues, never solver output.
 */
export const TRANSITION_FIXTURES: TransitionFixture[] = [
  { id: 'M01-flat-d-mismatch', incompatibilityClass: 'analytic-d-mismatch', p1: [5, 0, 0], p2: [7, 0, 0], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: Distance d=5 vs d=7, Δplan=2' },
  { id: 'M02-dist-relEl', incompatibilityClass: 'analytic-d-mismatch', p1: [5, 0, 0], p2: [5, 0, 2], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: Distance vs RelativeElevation analogue, same plan, Δz=2' },
  { id: 'M03-relEl-el', incompatibilityClass: 'analytic-d-mismatch', p1: [4, 1, 3], p2: [6, -1, 5], memberLength: 24, maxSearchDistance: 12, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: RelativeElevation vs Elevation analogue' },
  { id: 'M04-same-d-diff-z', incompatibilityClass: 'same-d-diff-z', p1: [5, 0, 1], p2: [5, 0, 4], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: same plan d, join Z law differs, Δz=3' },
  { id: 'M05-sloped-disagree', incompatibilityClass: 'sloped-disagree', p1: [5, 0.5, 1], p2: [6.5, -0.5, 3], memberLength: 22, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: sloped members, terminal solutions disagree' },
  { id: 'M06-joint-z-step', incompatibilityClass: 'joint-z-step', p1: [5, 0, 0], p2: [5, 0, 1.5], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: source joint Z step 1.5m analogue' },
  { id: 'M07-tie-control', incompatibilityClass: 'exact-tie-control', p1: [5, 0, 2], p2: [5, 0, 2], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic control: identical terminals, must need no transition' },
  { id: 'M08-tie-control-ulp', incompatibilityClass: 'exact-tie-control', p1: [5, 0, 2], p2: [5 + 4 * Number.EPSILON * 5, 0, 2], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic control: ULP-level twins, study agreement control must tie' },
  { id: 'M09-surf-analytic-gap', incompatibilityClass: 'surface-analytic', p1: [3, 0, 1], p2: [6, 0, 1], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic analogue inspired by 20J GAP shape, Δplan=3; assumed valid, not solver output' },
  { id: 'M10-surf-analytic-overlap', incompatibilityClass: 'surface-analytic', p1: [6, 0, 1], p2: [4, 0.5, 1.2], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: surface↔analytic OVERLAP analogue' },
  { id: 'M11-surf-surf', incompatibilityClass: 'surface-surface', p1: [2, 1, 0], p2: [5, -1, 0.5], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: surface↔surface daylight terminals disagree' },
  { id: 'M12-no-root', incompatibilityClass: 'root-ambiguity', p1: [5, 0, 0], p2: [7, 0, 0], memberLength: 20, maxSearchDistance: 2, roots: 0, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: no target root within maxSearch; terminals disagree so study control cannot mask it' },
  { id: 'M13-one-root', incompatibilityClass: 'root-ambiguity', p1: [5, 0, 0], p2: [7, 0, 0], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: unique root; transition still needs width' },
  { id: 'M14-multi-root', incompatibilityClass: 'root-ambiguity', p1: [5, 0, 0], p2: [7, 0, 1], memberLength: 20, maxSearchDistance: 10, roots: 2, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: two target roots, branch choice underdetermined' },
  { id: 'M15-line-line', incompatibilityClass: 'analytic-d-mismatch', p1: [5, 0, 0], p2: [8, 0, 0], memberLength: 30, maxSearchDistance: 12, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: line↔line d mismatch Δ=3' },
  { id: 'M16-line-arc', incompatibilityClass: 'line-arc', p1: [5, 0, 0], p2: [6.5, 1, 0], memberLength: 24, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-arc', note: 'Synthetic: line↔arc terminals disagree' },
  { id: 'M17-arc-line', incompatibilityClass: 'line-arc', p1: [6.5, 1, 0], p2: [5, 0, 0.5], memberLength: 24, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-arc', note: 'Synthetic: arc↔line terminals disagree (reversal of M16)' },
  { id: 'M18-arc-arc', incompatibilityClass: 'arc-arc', p1: [5, 1, 0], p2: [7, -1, 0], memberLength: 24, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'arc-arc', note: 'Synthetic analogue inspired by 20K arc-pair exclusion; study no-go by analogy, production exclusion unchanged' },
  { id: 'M19-closed', incompatibilityClass: 'closed-route', p1: [5, 0, 0], p2: [7, 0, 0], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: true, spanKind: 'line-line', note: 'Synthetic: closed-route negative/control' },
  { id: 'M20-near-zero', incompatibilityClass: 'analytic-d-mismatch', p1: [5, 0, 0], p2: [5.001, 0, 0], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: near-zero span 1mm, study control or micro-transition?' },
  { id: 'M21-large-span', incompatibilityClass: 'analytic-d-mismatch', p1: [5, 0, 0], p2: [15, 0, 5], memberLength: 60, maxSearchDistance: 20, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: large span Δplan=10 vs member length' },
  { id: 'M22-maxsearch-edge', incompatibilityClass: 'analytic-d-mismatch', p1: [9.9, 0, 0], p2: [10.1, 0, 0], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: terminals straddle maxSearchDistance' },
  { id: 'M23-extension', incompatibilityClass: 'surface-analytic', p1: [5, 0, 0], p2: [14, 0, 0], memberLength: 20, maxSearchDistance: 10, roots: 1, extensionNeeded: true, closed: false, spanKind: 'line-line', note: 'Synthetic: outside-extension analogue, target bounds exceeded' },
  { id: 'M24-sloped-step', incompatibilityClass: 'sloped-disagree', p1: [4, 0, 2], p2: [4, 0, 5], memberLength: 18, maxSearchDistance: 10, roots: 1, extensionNeeded: false, closed: false, spanKind: 'line-line', note: 'Synthetic: pure-Z sloped disagreement Δz=3' },
];

/**
 * Study agreement control assembled from imported 20J1 components. It is a
 * CONTROL for the study's tie fixtures only — not the production
 * exact-common-tie gate (production additionally uses anchored
 * leverage/gradient/FLOOR context absent here).
 */
const studyAgreementControl = (f: TransitionFixture): boolean => {
  const scale = Math.max(1, Math.abs(f.p1[0]), Math.abs(f.p1[1]), Math.abs(f.p2[0]), Math.abs(f.p2[1]));
  const tolX = coordinateAgreementTol(f.p1[0], f.p2[0], scale);
  const tolY = coordinateAgreementTol(f.p1[1], f.p2[1], scale);
  const tolZ = elevationAgreementTol(f.p1[2], f.p2[2], []);
  const floor = zeroDelta(f.p1[2], f.p2[2]);
  return (
    Math.abs(f.p1[0] - f.p2[0]) <= Math.max(tolX, 0) &&
    Math.abs(f.p1[1] - f.p2[1]) <= Math.max(tolY, 0) &&
    Math.abs(f.p1[2] - f.p2[2]) <= Math.max(tolZ, floor)
  );
};

const TIE_REASON =
  'Study agreement control: P1≈P2 under study control assembled from shared 20J1 components; no transition required (control only, not the production gate)';

const classify = (f: TransitionFixture, tied: boolean, deltaPlan: number): { c: Verdict; reason: string } => {
  if (tied) return { c: 'EXACT_COMMON_TIE_CONTROL', reason: TIE_REASON };
  if (f.closed) return { c: 'CLOSED_ROUTE_POLICY_REQUIRED', reason: 'Closed-route transition changes annulus topology; new topology policy required' };
  if (f.spanKind === 'arc-arc') return { c: 'ARC_PAIR_NO_GO', reason: 'Arc×arc pair: study no-go by analogy with the production arc-pair exclusion (exclusion itself unchanged)' };
  if (f.roots === 0) return { c: 'ROOT_POLICY_REQUIRED', reason: 'No target root within maxSearchDistance; nothing to transition to' };
  if (f.roots > 1) return { c: 'ROOT_POLICY_REQUIRED', reason: 'Multiple target roots; branch choice has no existing authority' };
  if (f.extensionNeeded) return { c: 'EXTENSION_POLICY_REQUIRED', reason: 'Transition would leave target bounds/maxSearchDistance; extension permission is policy' };
  void deltaPlan;
  return { c: 'TRANSITION_WIDTH_UNDERDETERMINED', reason: 'T0 segment exists geometrically but any finite-width T1 blend needs width/blend/criterion policy' };
};

export const evaluateFixture = (f: TransitionFixture): TransitionRow[] => {
  const origin: [number, number, number] = [f.p1[0], f.p1[1], f.p1[2]];
  const a = local(f.p1, origin);
  const b = local(f.p2, origin);
  const deltaPlan = Math.hypot(b[0] - a[0], b[1] - a[1]);
  const deltaZ = Math.abs(b[2] - a[2]);
  const tied = studyAgreementControl(f);
  const L = Math.hypot(b[0] - a[0], b[1] - a[1], b[2] - a[2]);
  // Translated-world numerical stress: rebuild both points in frames shifted
  // by s and re-measure plan separation. Reports the max deviation; the test
  // bounds it (<1e-6). This measures float sensitivity, not invariance.
  let maxDev = 0;
  for (const s of [1e6, 1e8]) {
    const o: [number, number, number] = [s, -s, s];
    const sa = local(f.p1, o);
    const sb = local(f.p2, o);
    const dPlan = Math.hypot(sb[0] - sa[0], sb[1] - sa[1]);
    maxDev = Math.max(maxDev, Math.abs(dPlan - deltaPlan));
  }
  // Mirror check: mirror the INPUTS (x → −x), recompute mirrored plan
  // separation from the mirrored points, and re-run control + classify.
  const mf: TransitionFixture = { ...f, p1: [-f.p1[0], f.p1[1], f.p1[2]], p2: [-f.p2[0], f.p2[1], f.p2[2]] };
  const mDeltaPlan = Math.hypot(mf.p2[0] - mf.p1[0], mf.p2[1] - mf.p1[1]);
  const mirrorStable = classify(mf, studyAgreementControl(mf), mDeltaPlan).c === classify(f, tied, deltaPlan).c;
  const base = classify(f, tied, deltaPlan);
  // T0 row: direct connector. Midpoint gaps are honestly nonzero whenever Δ>0.
  const t0: TransitionRow = {
    fixtureId: f.id, synthetic: true, incompatibilityClass: f.incompatibilityClass, candidate: 'T0',
    deltaPlan: r12(deltaPlan), deltaZ: r12(deltaZ), studyAgreementTie: tied,
    connectorLength: r12(L),
    midpointGapPlanIllustration: r12(deltaPlan / 2), midpointGapZIllustration: r12(deltaZ / 2),
    widthA: null, widthB: null, areaA: null, areaB: null, zVolA: null, zVolB: null,
    widthUnderdetermined: false, requiresNewCriterion: !tied,
    transformMaxDev: r12(maxDev), mirrorStable,
    classification: tied ? 'EXACT_COMMON_TIE_CONTROL' : base.c === 'TRANSITION_WIDTH_UNDERDETERMINED' ? 'TRANSITION_REQUIRES_NEW_CRITERION' : base.c,
    reasonCode: tied ? base.reason : `${base.reason} | T0 interior points differ from both terminals; interiors satisfy neither member law (see decision §6 production forensics — worker agreement would reject them), so truthful provenance needs a new transition criterion`,
  };
  // T1 row: two synthetic probe widths (memberLength/8 and 3× that) show
  // underdetermination. Exact deterministic check: the probes differ by
  // construction, so their illustrations must differ too.
  const wA = f.memberLength / 8;
  const wB = 3 * wA;
  const areaA = 0.5 * deltaPlan * wA;
  const areaB = 0.5 * deltaPlan * wB;
  const zVolA = 0.5 * deltaZ * wA;
  const zVolB = 0.5 * deltaZ * wB;
  const under = !tied && base.c === 'TRANSITION_WIDTH_UNDERDETERMINED' && wB !== wA;
  const probeEvidence =
    areaA !== areaB
      ? `probe plan areas differ ${r12(areaA)} vs ${r12(areaB)}`
      : `plan areas both ${r12(areaA)} by construction (pure-Z); probe Z-volumes differ ${r12(zVolA)} vs ${r12(zVolB)}`;
  const t1: TransitionRow = {
    fixtureId: f.id, synthetic: true, incompatibilityClass: f.incompatibilityClass, candidate: 'T1',
    deltaPlan: r12(deltaPlan), deltaZ: r12(deltaZ), studyAgreementTie: tied,
    connectorLength: r12(L),
    midpointGapPlanIllustration: r12(deltaPlan / 2), midpointGapZIllustration: r12(deltaZ / 2),
    widthA: r12(wA), widthB: r12(wB), areaA: r12(areaA), areaB: r12(areaB),
    zVolA: r12(zVolA), zVolB: r12(zVolB),
    widthUnderdetermined: under, requiresNewCriterion: !tied,
    transformMaxDev: r12(maxDev), mirrorStable,
    classification: tied ? 'EXACT_COMMON_TIE_CONTROL' : base.c,
    reasonCode: tied ? base.reason : under
      ? `${base.reason} | ${probeEvidence}: no existing authority selects width`
      : base.reason,
  };
  return [t0, t1];
};

export const buildCorpus = (): TransitionRow[] => {
  const rows: TransitionRow[] = [];
  const sorted = [...TRANSITION_FIXTURES].sort((x, y) => (x.id < y.id ? -1 : 1));
  for (const f of sorted) rows.push(...evaluateFixture(f));
  return rows;
};

export const corpusSha256 = (rows: TransitionRow[]): string =>
  createHash('sha256').update(JSON.stringify(rows)).digest('hex');

/** CLI: regenerate docs/evidence/phase20m/corpus.json + corpus.sha256. */
if (process.argv[1]?.endsWith('phase20mTransitionStudy.ts')) {
  const rows = buildCorpus();
  const dir = join(dirname(new URL(import.meta.url).pathname), '..', 'docs', 'evidence', 'phase20m');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'corpus.json'), `${JSON.stringify(rows, null, 2)}\n`);
  writeFileSync(join(dir, 'corpus.sha256'), `${corpusSha256(rows)}\n`);
  console.log(`phase20m corpus: ${rows.length} rows, sha=${corpusSha256(rows)}`);
}
