import { readFileSync } from 'node:fs';
import { DEFAULT_INPUT } from '../../src/defaultInput';
import { DEFAULT_CANADA_CRS_ID } from '../../src/engine/crsCatalog';
import {
  DEFAULT_QFIX_ANGULAR_SIGMA_SEC,
  DEFAULT_QFIX_LINEAR_SIGMA_M,
  DEFAULT_S9_INSTRUMENT_CENTERING_HORIZ_M,
} from '../../src/engine/defaults';
import type { InstrumentLibrary } from '../../src/types';
import type { RunSessionRequest } from '../../src/engine/runSession';

const buildInstrumentLibrary = (): InstrumentLibrary => ({
  S9: {
    code: 'S9',
    desc: 'industry standard S9 0.5"',
    edm_const: 0.001,
    edm_ppm: 1,
    hzPrecision_sec: 0.5,
    dirPrecision_sec: 0.5,
    azBearingPrecision_sec: 0.5,
    vaPrecision_sec: 0.5,
    instCentr_m: DEFAULT_S9_INSTRUMENT_CENTERING_HORIZ_M,
    tgtCentr_m: 0,
    vertCentr_m: 0,
    elevDiff_const_m: 0,
    elevDiff_ppm: 0,
    gpsStd_xy: 0,
    levStd_mmPerKm: 0,
  },
});

export const createRunSessionRequest = (
  overrides: Partial<RunSessionRequest> = {},
): RunSessionRequest => ({
  input: DEFAULT_INPUT,
  lastRunInput: null,
  maxIterations: 10,
  convergenceLimit: 0.01,
  units: 'm',
  parseSettings: {
    solveProfile: 'industry-parity',
    coordMode: '3D',
    coordSystemMode: 'local',
    crsId: DEFAULT_CANADA_CRS_ID,
    localDatumScheme: 'average-scale',
    averageScaleFactor: 1,
    commonElevation: 0,
    averageGeoidHeight: 0,
    gnssVectorFrameDefault: 'gridNEU',
    gnssFrameConfirmed: false,
    verticalDeflectionNorthSec: 0,
    verticalDeflectionEastSec: 0,
    observationMode: {
      bearing: 'grid',
      distance: 'measured',
      angle: 'measured',
      direction: 'measured',
    },
    gridBearingMode: 'grid',
    gridDistanceMode: 'measured',
    gridAngleMode: 'measured',
    gridDirectionMode: 'measured',
    runMode: 'adjustment',
    preanalysisMode: false,
    clusterDetectionEnabled: false,
    autoSideshotEnabled: true,
    autoAdjustEnabled: false,
    autoAdjustMaxCycles: 3,
    autoAdjustMaxRemovalsPerCycle: 1,
    autoAdjustStdResThreshold: 4,
    suspectImpactMode: 'auto',
    order: 'EN',
    angleUnits: 'dms',
    angleStationOrder: 'atfromto',
    angleMode: 'auto',
    deltaMode: 'slope',
    mapMode: 'off',
    mapScaleFactor: 1,
    normalize: true,
    faceNormalizationMode: 'on',
    applyCurvatureRefraction: false,
    refractionCoefficient: 0.13,
    verticalReduction: 'none',
    levelWeight: undefined,
    levelLoopToleranceBaseMm: 0,
    levelLoopTolerancePerSqrtKmMm: 4,
    crsTransformEnabled: false,
    crsProjectionModel: 'legacy-equirectangular',
    crsLabel: '',
    crsGridScaleEnabled: false,
    crsGridScaleFactor: 1,
    crsConvergenceEnabled: false,
    crsConvergenceAngleRad: 0,
    geoidModelEnabled: false,
    geoidModelId: 'NGS-DEMO',
    geoidSourceFormat: 'builtin',
    geoidSourcePath: '',
    geoidInterpolation: 'bilinear',
    geoidHeightConversionEnabled: false,
    geoidOutputHeightDatum: 'orthometric',
    gpsLoopCheckEnabled: false,
    gpsAddHiHtEnabled: false,
    gpsAddHiHtHiM: 0,
    gpsAddHiHtHtM: 0,
    qFixLinearSigmaM: DEFAULT_QFIX_LINEAR_SIGMA_M,
    qFixAngularSigmaSec: DEFAULT_QFIX_ANGULAR_SIGMA_SEC,
    prismEnabled: false,
    prismOffset: 0,
    prismScope: 'global',
    descriptionReconcileMode: 'first',
    descriptionAppendDelimiter: ' | ',
    lonSign: 'west-negative',
    tsCorrelationEnabled: false,
    tsCorrelationRho: 0.25,
    tsCorrelationScope: 'set',
    robustMode: 'none',
    robustK: 1.5,
    parseCompatibilityMode: 'strict',
    parseModeMigrated: true,
  },
  projectInstruments: buildInstrumentLibrary(),
  selectedInstrument: 'S9',
  projectIncludeFiles: {},
  geoidSourceData: null,
  excludedIds: [],
  overrides: {},
  approvedClusterMerges: [],
  ...overrides,
});

const extractTraverseStartupInput = (): string => {
  const raw = readFileSync('tests/fixtures/industry_case_traverse_output.txt', 'utf-8');
  const lines = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  const traverseOnlyLine = lines.findIndex((line) => line.trim() === '#Traverse Only');
  return (traverseOnlyLine > 0 ? lines.slice(Math.max(0, traverseOnlyLine - 1)) : lines)
    .join('\n')
    .trim();
};

const buildTraverseInstrumentLibrary = (): InstrumentLibrary => ({
  S9: {
    code: 'S9',
    desc: 'corrections from isopropyl',
    edm_const: 0.003,
    edm_ppm: 2,
    hzPrecision_sec: 1.2357,
    dirPrecision_sec: 0.87377,
    azBearingPrecision_sec: 0.707107,
    vaPrecision_sec: 3.28473,
    instCentr_m: 0.0015,
    tgtCentr_m: 0.0015,
    vertCentr_m: 0.0005,
    elevDiff_const_m: 0.01524,
    elevDiff_ppm: 0,
    gpsStd_xy: 0,
    levStd_mmPerKm: 0,
  },
  SX12: {
    code: 'SX12',
    desc: 'n/a',
    edm_const: 0.003,
    edm_ppm: 1.5,
    hzPrecision_sec: 0.950079,
    dirPrecision_sec: 0.671807,
    azBearingPrecision_sec: 1.414,
    vaPrecision_sec: 6.064437,
    instCentr_m: 0.0015,
    tgtCentr_m: 0.0015,
    vertCentr_m: 0.0005,
    elevDiff_const_m: 0.01524,
    elevDiff_ppm: 0,
    gpsStd_xy: 0,
    levStd_mmPerKm: 0,
  },
  TS11: {
    code: 'TS11',
    desc: 'n/a',
    edm_const: 0.002,
    edm_ppm: 1.5,
    hzPrecision_sec: 1.84146,
    dirPrecision_sec: 1.302108,
    azBearingPrecision_sec: 4,
    vaPrecision_sec: 4.41756,
    instCentr_m: 0.0015,
    tgtCentr_m: 0.0015,
    vertCentr_m: 0.0005,
    elevDiff_const_m: 0.01524,
    elevDiff_ppm: 0,
    gpsStd_xy: 0,
    levStd_mmPerKm: 0,
  },
  TRAV_DEFAULT: {
    code: 'TRAV_DEFAULT',
    desc: 'industry parity traverse project default',
    edm_const: 0.001,
    edm_ppm: 1.5,
    hzPrecision_sec: 1.414,
    dirPrecision_sec: 1,
    azBearingPrecision_sec: 1.414,
    vaPrecision_sec: 1,
    instCentr_m: 0.00075,
    tgtCentr_m: 0.00075,
    vertCentr_m: 0.0005,
    elevDiff_const_m: 0.01524,
    elevDiff_ppm: 0,
    gpsStd_xy: 0,
    levStd_mmPerKm: 1.5,
  },
});

export const createTraverseRunSessionRequest = (
  overrides: Partial<RunSessionRequest> = {},
): RunSessionRequest =>
  createRunSessionRequest({
    input: extractTraverseStartupInput(),
    convergenceLimit: 0.01,
    parseSettings: {
      ...createRunSessionRequest().parseSettings,
      coordMode: '3D',
      coordSystemMode: 'grid',
      crsId: 'CA_NAD83_CSRS_NB_STEREO_DOUBLE',
      order: 'NE',
      deltaMode: 'slope',
      angleStationOrder: 'atfromto',
      lonSign: 'west-positive',
      verticalDeflectionNorthSec: -2.91,
      verticalDeflectionEastSec: -1.46,
      applyCurvatureRefraction: true,
      verticalReduction: 'curvref',
      refractionCoefficient: 0.07,
    },
    projectInstruments: buildTraverseInstrumentLibrary(),
    selectedInstrument: 'TRAV_DEFAULT',
    ...overrides,
  });
