import type { AdjustmentResult } from '../../src/types';
export const buildResult = (): AdjustmentResult =>
  ({
    success: true,
    converged: true,
    iterations: 3,
    stations: {
      CTRL: {
        x: 1000,
        y: 2000,
        h: 10,
        fixed: true,
      },
      P1: {
        x: 1001.2345,
        y: 2002.3456,
        h: 11.5,
        fixed: false,
        latDeg: 45.123456789,
        lonDeg: -63.987654321,
      },
      LOST1: {
        x: 999.5,
        y: 1999.5,
        h: 9.5,
        fixed: false,
        lost: true,
      },
    },
    observations: [],
    logs: [],
    seuw: 1,
    dof: 1,
    parseState: {
      units: 'm',
      coordMode: '3D',
      order: 'EN',
      angleUnits: 'dms',
      angleStationOrder: 'atfromto',
      deltaMode: 'slope',
      mapMode: 'off',
      normalize: true,
      lonSign: 'west-negative',
      currentInstrument: '',
      edmMode: 'additive',
      applyCentering: true,
      addCenteringToExplicit: false,
      debug: false,
      angleMode: 'auto',
      verticalReduction: 'none',
      tsCorrelationEnabled: false,
      tsCorrelationScope: 'set',
      tsCorrelationRho: 0.25,
      robustMode: 'none',
      robustK: 1.5,
      autoAdjustEnabled: false,
      autoAdjustMaxCycles: 3,
      autoAdjustMaxRemovalsPerCycle: 1,
      autoAdjustStdResThreshold: 4,
      autoSideshotEnabled: true,
      qFixLinearSigmaM: 1e-7,
      qFixAngularSigmaSec: 1.0001e-3,
      descriptionReconcileMode: 'first',
      descriptionAppendDelimiter: ' | ',
      crsTransformEnabled: false,
      crsProjectionModel: 'legacy-equirectangular',
      crsLabel: '',
      crsGridScaleEnabled: false,
      crsGridScaleFactor: 1,
      crsConvergenceEnabled: false,
      crsConvergenceAngleRad: 0,
      geoidModelEnabled: false,
      geoidModelId: 'NGS-DEMO',
      geoidInterpolation: 'bilinear',
      geoidHeightConversionEnabled: false,
      geoidOutputHeightDatum: 'orthometric',
      gpsVectorMode: 'network',
      gpsAddHiHtEnabled: false,
      gpsAddHiHtHiM: 0,
      gpsAddHiHtHtM: 0,
      gpsLoopCheckEnabled: false,
      mapScaleFactor: 1,
      levelLoopToleranceBaseMm: 0,
      levelLoopTolerancePerSqrtKmMm: 4,
      reconciledDescriptions: {
        P1: 'Main point, near stairs',
      },
    },
  }) as AdjustmentResult;
